"""Runtime and distribution compatibility versions."""

__version__ = "1.1.2.dev0"
RUNTIME_ABI_VERSION = 1
GENERATED_WRAPPER_ABI_VERSION = 1
RUNTIME_DISTRIBUTION = "crabwalk-lang"
RUNTIME_COMPATIBILITY_SPECIFIER = ">=1.1,<1.2"
RUNTIME_DISTRIBUTION_REQUIREMENT = (
    f"{RUNTIME_DISTRIBUTION}{RUNTIME_COMPATIBILITY_SPECIFIER}"
)
PREBUILT_MANIFEST_SCHEMA_VERSION = 5
