"""Deterministic Rust and Cargo generation from semantic IR."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from crabwalk.diagnostics import SourceSpan

from .ir import (
    ArrayLiteralIR,
    AssignIR,
    AwaitIR,
    BinaryIR,
    BoolLiteralIR,
    BorrowIR,
    BreakIR,
    CallIR,
    ClosureIR,
    CompareIR,
    ConstructorIR,
    ContinueIR,
    CrateCallIR,
    DestructureIR,
    Effect,
    EnumConstructorIR,
    EnumIR,
    ExpressionIR,
    ExpressionStatementIR,
    FloatLiteralIR,
    FieldAccessIR,
    FieldAssignIR,
    ForEachIR,
    ForRangeIR,
    FunctionIR,
    FunctionPointerTwiceIR,
    IfIR,
    IndexIR,
    IntLiteralIR,
    LetIR,
    LocalConstIR,
    MatchIR,
    MethodCallIR,
    NameIR,
    NativePrintlnIR,
    NoneLiteralIR,
    PackageIR,
    PanicIR,
    ParameterIR,
    PassIR,
    PatternMatchIR,
    PythonPrintIR,
    ReturnIR,
    StatementIR,
    StringLiteralIR,
    StructConstructorIR,
    StructIR,
    TraitIR,
    TraitCallIR,
    TypeRef,
    TupleLiteralIR,
    TryIR,
    UnaryIR,
    WhileIR,
)
from .naming import PYO3_CARGO_ALIAS, cargo_dependency_key, owned_class_names

PYO3_VERSION = "0.29.2"
CODEGEN_SCHEMA_VERSION = 29


@dataclass(frozen=True, slots=True)
class GeneratedProject:
    cargo_toml: str
    build_rs: str
    rust_source: str
    source_map: dict[str, object]
    ir_json: str


class _Writer:
    def __init__(self) -> None:
        self._lines: list[str] = []
        self._indent = 0
        self._map: list[dict[str, object]] = []

    def line(
        self,
        value: str = "",
        span: SourceSpan | None = None,
        kind: str = "generated",
    ) -> None:
        self._lines.append(f"{'    ' * self._indent}{value}" if value else "")
        if span is not None:
            self._map.append(
                {
                    "generated_line": len(self._lines),
                    "source": span.to_dict(),
                    "kind": kind,
                }
            )

    def enter(self) -> None:
        self._indent += 1

    def leave(self) -> None:
        if self._indent == 0:
            raise AssertionError("unbalanced writer indentation")
        self._indent -= 1

    def render(self) -> str:
        if self._indent:
            raise AssertionError("unbalanced writer indentation")
        return "\n".join(self._lines) + "\n"

    @property
    def mappings(self) -> list[dict[str, object]]:
        return list(self._map)


def generate_project(ir: PackageIR, extension_name: str) -> GeneratedProject:
    from .validation import validate_package_ir

    validate_package_ir(ir)
    writer = _Writer()
    domain_symbols = {value.symbol for value in ir.structs}
    domain_symbols.update(value.symbol for value in ir.enums)
    boundary_names = {
        function.rust_symbol for function in ir.functions if function.python_boundary
    }
    writer.line("// Generated by Crabwalk. Inspectable; do not edit.")
    writer.line(
        f"// IR schema: {ir.schema_version}; codegen schema: {CODEGEN_SCHEMA_VERSION}"
    )
    writer.line(f"extern crate {PYO3_CARGO_ALIAS} as pyo3;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        cargo_key = cargo_dependency_key(dependency.package, dependency.binding)
        writer.line(f"extern crate {cargo_key} as {dependency.binding};")
    writer.line(f"use {PYO3_CARGO_ALIAS}::prelude::*;")
    if any(_enum_has_heterogeneous_fields(value) for value in ir.enums):
        writer.line(f"use {PYO3_CARGO_ALIAS}::IntoPyObjectExt;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        if dependency.package == "rayon":
            writer.line(f"use {dependency.binding}::prelude::*;")
    writer.line("mod __crabwalk_ffi {")
    writer.enter()
    writer.line('unsafe extern "C" {')
    writer.enter()
    writer.line('#[link_name = "abs"]')
    writer.line("pub(super) fn c_abs(input: i32) -> i32;")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    _write_panic_boundary(writer)
    writer.line()
    _write_thread_pool(writer)
    writer.line()

    if any(function.is_async for function in ir.functions):
        _write_block_on_executor(writer)
        writer.line()

    for trait in ir.traits:
        _write_native_trait(writer, trait)
        writer.line()

    for enum in ir.enums:
        _write_native_enum(writer, enum)
        writer.line()
        _write_owned_enum_class(writer, enum, domain_symbols)
        writer.line()

    for struct in ir.structs:
        _write_native_struct(writer, struct)
        writer.line()
        _write_owned_struct_class(writer, struct)
        writer.line()

    owned_vectors = _owned_vector_types(ir)
    for vector_type in owned_vectors:
        _write_owned_vector_class(writer, vector_type)
        writer.line()

    for function in ir.functions:
        _write_native_function(writer, function, boundary_names)
        writer.line()

    _write_method_impls(writer, ir)

    for function in ir.functions:
        if function.exported:
            _write_export_wrapper(writer, function, boundary_names)
            writer.line()

    writer.line(f'#[pymodule(name = "{extension_name}")]')
    writer.line("fn __crabwalk_module(m: &Bound<'_, PyModule>) -> PyResult<()> {")
    writer.enter()
    for function in ir.functions:
        if not function.exported:
            continue
        writer.line(
            f"m.add_function({PYO3_CARGO_ALIAS}::wrap_pyfunction!({function.rust_symbol}, m)?)?;",
            function.span,
            "abi_export",
        )
    for vector_type in owned_vectors:
        _, rust_class = owned_class_names(vector_type)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for struct in ir.structs:
        _, rust_class = owned_class_names(struct.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for enum in ir.enums:
        _, rust_class = owned_class_names(enum.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    writer.line("Ok(())")
    writer.leave()
    writer.line("}")

    package_name = "crabwalk-generated-module"
    dependencies = _cargo_dependencies(ir)
    cargo_toml = (
        "[package]\n"
        f'name = "{package_name}"\n'
        'version = "0.0.0"\n'
        'edition = "2024"\n'
        "publish = false\n\n"
        "[lib]\n"
        f'name = "{extension_name}"\n'
        'crate-type = ["cdylib"]\n\n'
        "[dependencies]\n"
        f'{PYO3_CARGO_ALIAS} = {{ package = "pyo3", version = "={PYO3_VERSION}", '
        'features = ["extension-module"] }\n'
        f"{dependencies}\n"
        "[build-dependencies]\n"
        f'pyo3-build-config = {{ version = "={PYO3_VERSION}" }}\n\n'
        "[profile.release]\n"
        "overflow-checks = true\n"
        'panic = "unwind"\n'
    )
    source_map = {
        "schema_version": 1,
        "generated_file": "src/lib.rs",
        "source_hash": ir.source_hash,
        "entries": writer.mappings,
    }
    return GeneratedProject(
        cargo_toml=cargo_toml,
        build_rs=(
            "fn main() {\n    pyo3_build_config::add_extension_module_link_args();\n}\n"
        ),
        rust_source=writer.render(),
        source_map=source_map,
        ir_json=json.dumps(ir.to_dict(), indent=2, sort_keys=True) + "\n",
    )


def _write_native_function(
    writer: _Writer,
    function: FunctionIR,
    boundary_names: set[str],
) -> None:
    parameters = ", ".join(
        (
            f"mut {parameter.name}: {parameter.type_ref.render()}"
            if parameter.mutable
            else f"{parameter.name}: {parameter.type_ref.render()}"
        )
        for parameter in function.parameters
    )
    native_return = (
        f"PyResult<{function.return_type.render()}>"
        if function.python_boundary
        else function.return_type.render()
    )
    generic_parameters = ""
    if function.type_parameters:
        rendered = []
        for parameter in function.type_parameters:
            if parameter.is_lifetime:
                rendered.append(f"'{parameter.name}")
            else:
                qualified_bounds = tuple(
                    {
                        "Debug": "std::fmt::Debug",
                        "Display": "std::fmt::Display",
                    }.get(value, value)
                    for value in parameter.bounds
                )
                bounds = f": {' + '.join(qualified_bounds)}" if qualified_bounds else ""
                rendered.append(f"{parameter.name}{bounds}")
        generic_parameters = f"<{', '.join(rendered)}>"
    writer.line(
        (
            f"{'async ' if function.is_async else ''}fn "
            f"__cw_native_{function.rust_symbol}{generic_parameters}"
            f"({parameters}) -> {native_return} {{"
        ),
        function.span,
        "function",
    )
    writer.enter()
    for statement in function.body:
        _write_statement(
            writer,
            statement,
            boundary_names,
            function.python_boundary,
        )
    if function.return_type.rust_name == "Unit" and not _ends_with_return(
        function.body
    ):
        writer.line(
            "Ok(())" if function.python_boundary else "()",
            function.span,
            "implicit_unit_return",
        )
    writer.leave()
    writer.line("}")


def _write_native_struct(writer: _Writer, struct: StructIR) -> None:
    derives = ["Clone", "Debug"] + ["::".join(value) for value in struct.derives]
    writer.line(f"#[derive({', '.join(derives)})]", struct.span, "struct_derive")
    writer.line(f"struct {struct.symbol} {{", struct.span, "struct")
    writer.enter()
    for field in struct.fields:
        writer.line(
            f"pub {field.name}: {field.type_ref.render()},",
            field.span,
            "struct_field",
        )
    writer.leave()
    writer.line("}")


def _write_native_trait(writer: _Writer, trait: TraitIR) -> None:
    writer.line(f"trait {trait.symbol} {{", trait.span, "trait")
    writer.enter()
    for method in trait.methods:
        writer.line(
            f"fn {method.name}(&self) -> {method.return_type.render()};",
            method.span,
            "trait_method",
        )
    writer.leave()
    writer.line("}")


def _write_method_impls(writer: _Writer, package: PackageIR) -> None:
    inherent = [
        function
        for function in package.functions
        if function.method_for is not None
        and function.trait_symbol is None
        and function.operator_kind is None
    ]
    for function in inherent:
        assert function.method_for is not None and function.method_name is not None
        writer.line(f"impl {function.method_for.render()} {{")
        writer.enter()
        _write_method_glue(writer, function)
        writer.leave()
        writer.line("}")
        writer.line()

    operators = [
        function
        for function in package.functions
        if function.method_for is not None and function.operator_kind is not None
    ]
    for function in operators:
        assert function.method_for is not None
        assert function.operator_kind == "add"
        assert len(function.parameters) == 2
        right = function.parameters[1]
        writer.line(
            f"impl std::ops::Add<{right.type_ref.render()}> "
            f"for {function.method_for.render()} {{"
        )
        writer.enter()
        writer.line(f"type Output = {function.return_type.render()};")
        writer.line()
        writer.line(
            f"fn add(self, {right.name}: {right.type_ref.render()}) -> Self::Output {{",
            function.span,
            "operator_impl",
        )
        writer.enter()
        writer.line(f"__cw_native_{function.rust_symbol}(self, {right.name})")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
        writer.line()

    trait_groups: dict[tuple[str, str], list[FunctionIR]] = {}
    for function in package.functions:
        if function.method_for is None or function.trait_symbol is None:
            continue
        trait_groups.setdefault(
            (function.trait_symbol, function.method_for.rust_name), []
        ).append(function)
    for (trait_symbol, _), functions in trait_groups.items():
        target = functions[0].method_for
        assert target is not None
        writer.line(f"impl {trait_symbol} for {target.render()} {{")
        writer.enter()
        for function in functions:
            _write_method_glue(writer, function)
        writer.leave()
        writer.line("}")
        writer.line()


def _write_method_glue(writer: _Writer, function: FunctionIR) -> None:
    assert function.method_name is not None and function.parameters
    receiver_type = function.parameters[0].type_ref
    receiver = {
        "Ref": "&self",
        "Mut": "&mut self",
        "Owned": "self",
    }[receiver_type.rust_name]
    tail = [
        f"{parameter.name}: {parameter.type_ref.render()}"
        for parameter in function.parameters[1:]
    ]
    parameters = ", ".join((receiver, *tail))
    arguments = ", ".join(
        ("self", *(parameter.name for parameter in function.parameters[1:]))
    )
    writer.line(
        f"fn {function.method_name}({parameters}) -> {function.return_type.render()} {{",
        function.span,
        "method_impl",
    )
    writer.enter()
    writer.line(f"__cw_native_{function.rust_symbol}({arguments})")
    writer.leave()
    writer.line("}")


def _write_native_enum(writer: _Writer, enum: EnumIR) -> None:
    derives = ["Clone", "Debug"] + ["::".join(value) for value in enum.derives]
    writer.line(f"#[derive({', '.join(derives)})]", enum.span, "enum_derive")
    writer.line(f"enum {enum.symbol} {{", enum.span, "enum")
    writer.enter()
    for variant in enum.variants:
        if not variant.fields:
            writer.line(f"{variant.name},", variant.span, "enum_variant")
        elif variant.tuple_style:
            fields = ", ".join(field.type_ref.render() for field in variant.fields)
            writer.line(f"{variant.name}({fields}),", variant.span, "enum_variant")
        else:
            writer.line(f"{variant.name} {{", variant.span, "enum_variant")
            writer.enter()
            for field in variant.fields:
                writer.line(
                    f"{field.name}: {field.type_ref.render()},",
                    field.span,
                    "enum_field",
                )
            writer.leave()
            writer.line("},")
    writer.leave()
    writer.line("}")


def _write_owned_enum_class(
    writer: _Writer,
    enum: EnumIR,
    domain_symbols: set[str],
) -> None:
    python_name, rust_name = owned_class_names(enum.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{enum.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line("#[allow(non_snake_case)]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    for variant in enum.variants:
        if any(
            _type_contains_domain(field.type_ref, domain_symbols)
            for field in variant.fields
        ):
            writer.line(
                "// Nested domain payload construction stays inside compiled Rust."
            )
            continue
        parameters = ", ".join(
            f"{field.name}: {field.type_ref.render()}" for field in variant.fields
        )
        writer.line("#[staticmethod]")
        writer.line(f"fn {variant.name}({parameters}) -> Self {{")
        writer.enter()
        if not variant.fields:
            value = f"{enum.symbol}::{variant.name}"
        elif variant.tuple_style:
            arguments = ", ".join(field.name for field in variant.fields)
            value = f"{enum.symbol}::{variant.name}({arguments})"
        else:
            arguments = ", ".join(field.name for field in variant.fields)
            value = f"{enum.symbol}::{variant.name} {{ {arguments} }}"
        writer.line(f"Self {{ value: Some({value}) }}")
        writer.leave()
        writer.line("}")
        writer.line()
    writer.line("fn variant(&self) -> PyResult<&'static str> {")
    writer.enter()
    writer.line("match self.value.as_ref() {")
    writer.enter()
    for variant in enum.variants:
        pattern = _enum_variant_pattern(enum, variant.name, (), variant.tuple_style)
        writer.line(f'Some({pattern}) => Ok("{variant.name}"),')
    writer.line(
        f'None => Err({PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")),'
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    for field_name, candidate_types in sorted(field_types.items()):
        if any(
            _type_contains_domain(value, domain_symbols) for value in candidate_types
        ):
            writer.line()
            writer.line("// Nested domain payload getters stay inside compiled Rust.")
            continue
        heterogeneous = len(candidate_types) > 1
        field_type = next(iter(candidate_types))
        writer.line()
        writer.line("#[getter]")
        if heterogeneous:
            writer.line(
                f"fn {field_name}(&self, py: Python<'_>) -> "
                "PyResult<Option<Py<PyAny>>> {"
            )
        else:
            writer.line(
                f"fn {field_name}(&self) -> PyResult<Option<{field_type.render()}>> {{"
            )
        writer.enter()
        writer.line("let value = self.value.as_ref().ok_or_else(|| {")
        writer.enter()
        writer.line(
            f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
        )
        writer.leave()
        writer.line("})?;")
        writer.line("match value {")
        writer.enter()
        for variant in enum.variants:
            target = next(
                (field for field in variant.fields if field.name == field_name), None
            )
            if target is None:
                continue
            bindings = tuple(
                (field.name, "__target" if field.name == field_name else "")
                for field in variant.fields
            )
            pattern = _enum_variant_pattern(
                enum,
                variant.name,
                bindings,
                variant.tuple_style,
            )
            converted = (
                "__target.clone().into_py_any(py)?"
                if heterogeneous
                else "__target.clone()"
            )
            writer.line(f"{pattern} => Ok(Some({converted})),")
        writer.line("_ => Ok(None),")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(f'Some(value) => format!("{enum.name}({{:?}})", value),')
    writer.line(f'None => String::from("{enum.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _type_contains_domain(type_ref: TypeRef, domain_symbols: set[str]) -> bool:
    return type_ref.rust_name in domain_symbols or any(
        _type_contains_domain(value, domain_symbols) for value in type_ref.arguments
    )


def _enum_has_heterogeneous_fields(enum: EnumIR) -> bool:
    """Return whether one Python-visible payload name has multiple Rust types.

    Rust tuple variants conventionally reuse positional names such as ``_0`` even
    though each variant is free to choose an unrelated payload type. PyO3 needs a
    single return type for a Python property, so those getters erase only the ABI
    representation to ``PyAny`` while the native enum remains fully typed.
    """

    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    return any(len(value) > 1 for value in field_types.values())


def _enum_variant_pattern(
    enum: EnumIR,
    variant_name: str,
    bindings: tuple[tuple[str, str], ...],
    tuple_style: bool,
) -> str:
    variant = next(value for value in enum.variants if value.name == variant_name)
    if not variant.fields:
        return f"{enum.symbol}::{variant.name}"
    values = {field: local for field, local in bindings}
    if tuple_style:
        patterns = ", ".join(values.get(field.name) or "_" for field in variant.fields)
        return f"{enum.symbol}::{variant.name}({patterns})"
    patterns = ", ".join(
        f"{field.name}: {values.get(field.name) or '_'}" for field in variant.fields
    )
    return f"{enum.symbol}::{variant.name} {{ {patterns} }}"


def _write_owned_struct_class(writer: _Writer, struct: StructIR) -> None:
    python_name, rust_name = owned_class_names(struct.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{struct.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    parameters = ", ".join(
        f"{field.name}: {field.type_ref.render()}" for field in struct.fields
    )
    writer.line("#[new]")
    writer.line(f"fn new({parameters}) -> Self {{")
    writer.enter()
    writer.line("Self { value: Some(" + struct.symbol + " {")
    writer.enter()
    for field in struct.fields:
        writer.line(f"{field.name},")
    writer.leave()
    writer.line("}) }")
    writer.leave()
    writer.line("}")
    for field in struct.fields:
        writer.line()
        writer.line("#[getter]")
        writer.line(f"fn {field.name}(&self) -> PyResult<{field.type_ref.render()}> {{")
        writer.enter()
        writer.line(
            f"self.value.as_ref().map(|value| value.{field.name}.clone()).ok_or_else(|| {{"
        )
        writer.enter()
        writer.line(
            f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
        )
        writer.leave()
        writer.line("})")
        writer.leave()
        writer.line("}")
        writer.line()
        writer.line("#[setter]")
        writer.line(
            f"fn set_{field.name}(&mut self, value: {field.type_ref.render()}) -> PyResult<()> {{"
        )
        writer.enter()
        writer.line("let target = self.value.as_mut().ok_or_else(|| {")
        writer.enter()
        writer.line(
            f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
        )
        writer.leave()
        writer.line("})?;")
        writer.line(f"target.{field.name} = value;")
        writer.line("Ok(())")
        writer.leave()
        writer.line("}")
    writer.line()
    tuple_types = ", ".join(field.type_ref.render() for field in struct.fields)
    tuple_values = ", ".join(f"value.{field.name}.clone()" for field in struct.fields)
    if len(struct.fields) == 1:
        tuple_types += ","
        tuple_values += ","
    writer.line(f"fn to_python(&self) -> PyResult<({tuple_types})> {{")
    writer.enter()
    writer.line("self.value.as_ref().map(|value| (")
    writer.enter()
    writer.line(tuple_values)
    writer.leave()
    writer.line(")).ok_or_else(|| {")
    writer.enter()
    writer.line(
        f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
    )
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(f'Some(value) => format!("{struct.name}({{:?}})", value),')
    writer.line(f'None => String::from("{struct.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_export_wrapper(
    writer: _Writer,
    function: FunctionIR,
    boundary_names: set[str],
) -> None:
    wrapper_parameters = [
        _wrapper_parameter(parameter) for parameter in function.parameters
    ]
    releases_gil = function_releases_gil(function)
    if releases_gil:
        wrapper_parameters.insert(0, "py: Python<'_>")
    parameters = ", ".join(wrapper_parameters)
    arguments = ", ".join(
        (
            f"__cw_arg_{parameter.name}"
            if parameter.type_ref.ownership is not None
            else parameter.name
        )
        for parameter in function.parameters
    )
    writer.line("#[pyfunction]")
    wrapper_return = (
        f"PyResult<{function.return_type.arguments[0].render()}>"
        if function.return_type.rust_name == "Result"
        else f"PyResult<{function.return_type.render()}>"
    )
    writer.line(
        f"fn {function.rust_symbol}({parameters}) -> {wrapper_return} {{",
        function.span,
        "abi_wrapper",
    )
    writer.enter()
    for parameter in function.parameters:
        _write_wrapper_extraction(writer, parameter)
    if function.return_type.rust_name == "Result":
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if function.python_boundary:
            native_call += "?"
        elif releases_gil:
            native_call = f"py.detach(move || {native_call})"
        writer.line(
            f"let __cw_result = __cw_catch_panic(|| {native_call})?;",
            function.span,
            "panic_boundary",
        )
        if function.python_boundary:
            writer.line("let __cw_result = __cw_result?;")
        writer.line(
            "match __cw_result {",
            function.span,
            "abi_call",
        )
        writer.enter()
        writer.line("Ok(value) => Ok(value),")
        error_type = function.return_type.arguments[1].display()
        writer.line(
            f"Err(error) => Err({PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("
            f'format!("CrabwalkRustError: {error_type}: {{}}", error))),'
        )
        writer.leave()
        writer.line("}")
    elif function.python_boundary:
        writer.line(
            (f"__cw_catch_panic(|| __cw_native_{function.rust_symbol}({arguments}))?"),
            function.span,
            "abi_call",
        )
    else:
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            native_call = f"py.detach(move || {native_call})"
        writer.line(
            f"Ok(__cw_catch_panic(|| {native_call})?)",
            function.span,
            "abi_call",
        )
    writer.leave()
    writer.line("}")


def _write_panic_boundary(writer: _Writer) -> None:
    writer.line(
        "fn __cw_panic_message(payload: Box<dyn std::any::Any + Send>) -> String {"
    )
    writer.enter()
    writer.line("if let Some(value) = payload.downcast_ref::<&str>() {")
    writer.enter()
    writer.line("(*value).to_owned()")
    writer.leave()
    writer.line("} else if let Some(value) = payload.downcast_ref::<String>() {")
    writer.enter()
    writer.line("value.clone()")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line('String::from("Rust panic without a string payload")')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "fn __cw_catch_panic<T, F: FnOnce() -> T>(operation: F) -> PyResult<T> {"
    )
    writer.enter()
    writer.line(
        "match std::panic::catch_unwind(std::panic::AssertUnwindSafe(operation)) {"
    )
    writer.enter()
    writer.line("Ok(value) => Ok(value),")
    writer.line("Err(payload) => {")
    writer.enter()
    writer.line("let message = __cw_panic_message(payload);")
    writer.line(
        f'Err({PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err(format!("CrabwalkPanicError: {{}}", message)))'
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_thread_pool(writer: _Writer) -> None:
    writer.line("type __CwJob = Box<dyn FnOnce() + Send + 'static>;")
    writer.line(
        "type __CwWorkerFailure = std::sync::Arc<std::sync::Mutex<Option<String>>>;"
    )
    writer.line()
    writer.line(
        "fn __cw_record_worker_failure(failure: &__CwWorkerFailure, message: String) {"
    )
    writer.enter()
    writer.line(
        "let mut slot = failure.lock().unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("if slot.is_none() { *slot = Some(message); }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwThreadPool {")
    writer.enter()
    writer.line("workers: Vec<__CwWorker>,")
    writer.line("sender: Option<std::sync::mpsc::Sender<__CwJob>>,")
    writer.line("failure: __CwWorkerFailure,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwThreadPool {")
    writer.enter()
    writer.line("fn new(size: usize) -> Self {")
    writer.enter()
    writer.line('assert!(size > 0, "thread pool size must be positive");')
    writer.line("let (sender, receiver) = std::sync::mpsc::channel();")
    writer.line("let receiver = std::sync::Arc::new(std::sync::Mutex::new(receiver));")
    writer.line("let failure = std::sync::Arc::new(std::sync::Mutex::new(None));")
    writer.line("let mut workers = Vec::with_capacity(size);")
    writer.line("for id in 0..size {")
    writer.enter()
    writer.line(
        "workers.push(__CwWorker::new(id, std::sync::Arc::clone(&receiver), "
        "std::sync::Arc::clone(&failure)));"
    )
    writer.leave()
    writer.line("}")
    writer.line("Self { workers, sender: Some(sender), failure }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn execute<F>(&self, operation: F)")
    writer.line("where")
    writer.enter()
    writer.line("F: FnOnce() + Send + 'static,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let job = Box::new(operation);")
    writer.line("self.sender.as_ref().unwrap().send(job).unwrap();")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn finish(mut self) -> Result<(), String> {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.line("let failure = {")
    writer.enter()
    writer.line(
        "let mut slot = self.failure.lock()"
        ".unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("slot.take()")
    writer.leave()
    writer.line("};")
    writer.line("match failure { Some(message) => Err(message), None => Ok(()) }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn shutdown(&mut self) {")
    writer.enter()
    writer.line("drop(self.sender.take());")
    writer.line("for worker in self.workers.drain(..) {")
    writer.enter()
    writer.line("if let Err(payload) = worker.thread.join() {")
    writer.enter()
    writer.line(
        "__cw_record_worker_failure(&self.failure, __cw_panic_message(payload));"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl Drop for __CwThreadPool {")
    writer.enter()
    writer.line("fn drop(&mut self) {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwWorker {")
    writer.enter()
    writer.line("_id: usize,")
    writer.line("thread: std::thread::JoinHandle<()>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwWorker {")
    writer.enter()
    writer.line(
        "fn new(id: usize, receiver: "
        "std::sync::Arc<std::sync::Mutex<std::sync::mpsc::Receiver<__CwJob>>>, "
        "failure: __CwWorkerFailure) "
        "-> Self {"
    )
    writer.enter()
    writer.line("let thread = std::thread::spawn(move || loop {")
    writer.enter()
    writer.line("let message = receiver.lock()")
    writer.enter()
    writer.line(".unwrap_or_else(|poisoned| poisoned.into_inner())")
    writer.line(".recv();")
    writer.leave()
    writer.line("match message {")
    writer.enter()
    writer.line("Ok(job) => {")
    writer.enter()
    writer.line(
        "if let Err(payload) = std::panic::catch_unwind("
        "std::panic::AssertUnwindSafe(job)) {"
    )
    writer.enter()
    writer.line("__cw_record_worker_failure(&failure, __cw_panic_message(payload));")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("Err(_) => break,")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("});")
    writer.line("Self { _id: id, thread }")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_block_on_executor(writer: _Writer) -> None:
    """Emit the minimal std-only executor used by explicit rust.block_on calls.

    It is intentionally educational rather than a replacement for Tokio or async-std:
    a pending future yields the OS thread and is polled again. The implementation is
    safe Rust, deterministic, and sufficient for the self-contained Book examples.
    """

    writer.line("struct __CwNoopWake;")
    writer.line("impl std::task::Wake for __CwNoopWake {")
    writer.enter()
    writer.line("fn wake(self: std::sync::Arc<Self>) {}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_yield_now() {")
    writer.enter()
    writer.line("let mut yielded = false;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if yielded {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("yielded = true;")
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_sleep_millis(milliseconds: u64) {")
    writer.enter()
    writer.line(
        "let deadline = std::time::Instant::now() "
        "+ std::time::Duration::from_millis(milliseconds);"
    )
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if std::time::Instant::now() >= deadline {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_join2<A: std::future::Future, B: std::future::Future>(")
    writer.enter()
    writer.line("left: A,")
    writer.line("right: B,")
    writer.leave()
    writer.line(") -> (A::Output, B::Output) {")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("let mut left_output = None;")
    writer.line("let mut right_output = None;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if left_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("left_output = Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if right_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("right_output = Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if left_output.is_some() && right_output.is_some() {")
    writer.enter()
    writer.line(
        "std::task::Poll::Ready((left_output.take().unwrap(), "
        "right_output.take().unwrap()))"
    )
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_select2<A, B>(left: A, right: B) -> A::Output")
    writer.line("where")
    writer.enter()
    writer.line("A: std::future::Future,")
    writer.line("B: std::future::Future<Output = A::Output>,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "async fn __cw_recv_async<T>(receiver: &std::sync::mpsc::Receiver<T>) -> T {"
    )
    writer.enter()
    writer.line("std::future::poll_fn(|context| match receiver.try_recv() {")
    writer.enter()
    writer.line("Ok(value) => std::task::Poll::Ready(value),")
    writer.line("Err(std::sync::mpsc::TryRecvError::Empty) => {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.line(
        "Err(std::sync::mpsc::TryRecvError::Disconnected) => "
        'panic!("async channel disconnected"),'
    )
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __cw_block_on<F: std::future::Future>(future: F) -> F::Output {")
    writer.enter()
    writer.line(
        "let waker = std::task::Waker::from(std::sync::Arc::new(__CwNoopWake));"
    )
    writer.line("let mut context = std::task::Context::from_waker(&waker);")
    writer.line("let mut future = std::pin::pin!(future);")
    writer.line("loop {")
    writer.enter()
    writer.line("match std::future::Future::poll(future.as_mut(), &mut context) {")
    writer.enter()
    writer.line("std::task::Poll::Ready(value) => return value,")
    writer.line("std::task::Poll::Pending => std::thread::yield_now(),")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def function_releases_gil(function: FunctionIR) -> bool:
    """Whether an exported wrapper can detach from Python for the native call."""

    effects = set(function.effects)
    if effects & {
        Effect.PYTHON_RUNTIME,
        Effect.GLOBAL_MUTATION,
        Effect.UNSAFE_MEMORY,
        Effect.UNSAFE_FFI,
    }:
        return False
    if any(
        parameter.type_ref.ownership is not None for parameter in function.parameters
    ):
        return False
    safe_names = {
        "i8",
        "i16",
        "i32",
        "i64",
        "i128",
        "u8",
        "u16",
        "u32",
        "u64",
        "u128",
        "usize",
        "f32",
        "f64",
        "bool",
        "char",
        "Unit",
    }
    return (
        all(
            parameter.type_ref.rust_name in safe_names
            for parameter in function.parameters
        )
        and function.return_type.rust_name in safe_names
    )


def _write_statement(
    writer: _Writer,
    statement: StatementIR,
    boundary_names: set[str],
    current_boundary: bool,
) -> None:
    if isinstance(statement, ReturnIR):
        if current_boundary:
            value = (
                "return Ok(());"
                if statement.value is None
                else (
                    f"return Ok({_render_expression(statement.value, boundary_names)});"
                )
            )
        else:
            value = (
                "return;"
                if statement.value is None
                else (f"return {_render_expression(statement.value, boundary_names)};")
            )
        writer.line(value, statement.span, "return")
        return
    if isinstance(statement, LetIR):
        mutability = "mut " if statement.mutable else ""
        writer.line(
            (
                f"let {mutability}{statement.name}: {statement.type_ref.render()} "
                f"= {_render_expression(statement.value, boundary_names)};"
            ),
            statement.span,
            "let",
        )
        return
    if isinstance(statement, AssignIR):
        writer.line(
            (
                f"{statement.name} = "
                f"{_render_expression(statement.value, boundary_names)};"
            ),
            statement.span,
            "assign",
        )
        return
    if isinstance(statement, FieldAssignIR):
        writer.line(
            (
                f"{_render_place_expression(statement.receiver, boundary_names)}."
                f"{statement.field} = "
                f"{_render_expression(statement.value, boundary_names)};"
            ),
            statement.span,
            "field_assign",
        )
        return
    if isinstance(statement, DestructureIR):
        names = ", ".join(
            f"mut {name}" if mutable else name
            for name, mutable in zip(statement.names, statement.mutable)
        )
        writer.line(
            (
                f"let ({names}): {statement.type_ref.render()} = "
                f"{_render_expression(statement.value, boundary_names)};"
            ),
            statement.span,
            "tuple_destructure",
        )
        return
    if isinstance(statement, LocalConstIR):
        writer.line(
            (
                f"const {statement.name}: {statement.type_ref.render()} = "
                f"{_render_expression(statement.value, boundary_names)};"
            ),
            statement.span,
            "local_const",
        )
        return
    if isinstance(statement, ExpressionStatementIR):
        writer.line(
            f"{_render_expression(statement.value, boundary_names)};",
            statement.span,
            "expression_statement",
        )
        return
    if isinstance(statement, IfIR):
        writer.line(
            f"if {_render_expression(statement.condition, boundary_names)} {{",
            statement.condition.span,
            "if_condition",
        )
        writer.enter()
        for child in statement.body:
            _write_statement(writer, child, boundary_names, current_boundary)
        writer.leave()
        if statement.otherwise:
            writer.line("} else {", statement.span, "else")
            writer.enter()
            for child in statement.otherwise:
                _write_statement(writer, child, boundary_names, current_boundary)
            writer.leave()
        writer.line("}")
        return
    if isinstance(statement, WhileIR):
        writer.line(
            f"while {_render_expression(statement.condition, boundary_names)} {{",
            statement.condition.span,
            "while_condition",
        )
        writer.enter()
        for child in statement.body:
            _write_statement(writer, child, boundary_names, current_boundary)
        writer.leave()
        writer.line("}")
        return
    if isinstance(statement, ForRangeIR):
        writer.line(
            (
                f"for {statement.variable} in "
                f"{_render_expression(statement.start, boundary_names)}.."
                f"{_render_expression(statement.stop, boundary_names)} {{"
            ),
            statement.span,
            "for_range",
        )
        writer.enter()
        for child in statement.body:
            _write_statement(writer, child, boundary_names, current_boundary)
        writer.leave()
        writer.line("}")
        return
    if isinstance(statement, ForEachIR):
        writer.line(
            (
                f"for {statement.variable} in "
                f"{_render_expression(statement.iterator, boundary_names)} {{"
            ),
            statement.span,
            "for_each",
        )
        writer.enter()
        for child in statement.body:
            _write_statement(writer, child, boundary_names, current_boundary)
        writer.leave()
        writer.line("}")
        return
    if isinstance(statement, MatchIR):
        subject = _render_expression(statement.subject, boundary_names)
        borrowed = subject if statement.subject_borrowed else f"&{subject}"
        writer.line(
            f"match <{statement.enum_symbol} as Clone>::clone({borrowed}) {{",
            statement.span,
            "match",
        )
        writer.enter()
        for match_arm in statement.arms:
            if match_arm.variant is None:
                pattern = "_"
            elif not match_arm.bindings:
                pattern = f"{match_arm.enum_symbol}::{match_arm.variant}"
            elif match_arm.tuple_style:
                values = ", ".join(local or "_" for _, local in match_arm.bindings)
                pattern = f"{match_arm.enum_symbol}::{match_arm.variant}({values})"
            else:
                values = ", ".join(
                    f"{field}: {local or '_'}" for field, local in match_arm.bindings
                )
                pattern = f"{match_arm.enum_symbol}::{match_arm.variant} {{ {values} }}"
            writer.line(f"{pattern} => {{", match_arm.span, "match_arm")
            writer.enter()
            for child in match_arm.body:
                _write_statement(writer, child, boundary_names, current_boundary)
            writer.leave()
            writer.line("},")
        writer.leave()
        writer.line("}")
        return
    if isinstance(statement, PatternMatchIR):
        subject = _render_expression(statement.subject, boundary_names)
        borrowed = subject if statement.subject_borrowed else f"&{subject}"
        subject_type = statement.subject_type.render()
        writer.line(
            f"match <{subject_type} as Clone>::clone({borrowed}) {{",
            statement.span,
            "pattern_match",
        )
        writer.enter()
        for pattern_arm in statement.arms:
            guard = (
                ""
                if pattern_arm.guard is None
                else f" if {_render_expression(pattern_arm.guard, boundary_names)}"
            )
            writer.line(
                f"{pattern_arm.pattern}{guard} => {{",
                pattern_arm.span,
                "pattern_match_arm",
            )
            writer.enter()
            for child in pattern_arm.body:
                _write_statement(writer, child, boundary_names, current_boundary)
            writer.leave()
            writer.line("},")
        writer.leave()
        writer.line("}")
        return
    if isinstance(statement, BreakIR):
        writer.line("break;", statement.span, "break")
        return
    if isinstance(statement, ContinueIR):
        writer.line("continue;", statement.span, "continue")
        return
    if isinstance(statement, PassIR):
        writer.line("();", statement.span, "pass")
        return
    raise AssertionError(f"unhandled statement IR: {type(statement).__name__}")


def _render_expression(
    expression: ExpressionIR,
    boundary_names: set[str] | None = None,
) -> str:
    boundary_names = boundary_names or set()
    if isinstance(expression, IntLiteralIR):
        return f"{expression.value}{expression.type_ref.render()}"
    if isinstance(expression, FloatLiteralIR):
        value = repr(expression.value)
        if "." not in value and "e" not in value.lower():
            value += ".0"
        return f"{value}{expression.type_ref.render()}"
    if isinstance(expression, BoolLiteralIR):
        return "true" if expression.value else "false"
    if isinstance(expression, StringLiteralIR):
        if expression.type_ref.rust_name == "char":
            return _rust_char_literal(expression.value)
        literal = _rust_string_literal(expression.value)
        return (
            f"String::from({literal})"
            if expression.type_ref.rust_name == "String"
            else literal
        )
    if isinstance(expression, TupleLiteralIR):
        values = ", ".join(
            _render_expression(value, boundary_names) for value in expression.values
        )
        return f"({values}{',' if len(expression.values) == 1 else ''})"
    if isinstance(expression, ArrayLiteralIR):
        values = ", ".join(
            _render_expression(value, boundary_names) for value in expression.values
        )
        return f"[{values}]"
    if isinstance(expression, IndexIR):
        receiver = _render_expression(expression.receiver, boundary_names)
        if expression.receiver.type_ref.rust_name == "Tuple" and isinstance(
            expression.index, IntLiteralIR
        ):
            rendered = f"{receiver}.{expression.index.value}"
        else:
            rendered = (
                f"{receiver}[{_render_expression(expression.index, boundary_names)}]"
            )
        return rendered if _is_copy_type(expression.type_ref) else f"{rendered}.clone()"
    if isinstance(expression, NoneLiteralIR):
        return "()"
    if isinstance(expression, NameIR):
        return expression.name
    if isinstance(expression, BorrowIR):
        operator = "&mut " if expression.kind == "mutable" else "&"
        return f"{operator}{_render_place_expression(expression.value, boundary_names)}"
    if isinstance(expression, UnaryIR):
        operator = {"positive": "+", "negative": "-", "not": "!"}[expression.operator]
        return f"({operator}{_render_expression(expression.operand, boundary_names)})"
    if isinstance(expression, BinaryIR):
        operator = {
            "add": "+",
            "subtract": "-",
            "multiply": "*",
            "divide": "/",
            "remainder": "%",
            "and": "&&",
            "or": "||",
        }[expression.operator]
        return (
            f"({_render_expression(expression.left, boundary_names)} {operator} "
            f"{_render_expression(expression.right, boundary_names)})"
        )
    if isinstance(expression, CompareIR):
        operator = {
            "eq": "==",
            "not_eq": "!=",
            "lt": "<",
            "lt_eq": "<=",
            "gt": ">",
            "gt_eq": ">=",
        }[expression.operator]
        return (
            f"({_render_expression(expression.left, boundary_names)} {operator} "
            f"{_render_expression(expression.right, boundary_names)})"
        )
    if isinstance(expression, CallIR):
        arguments = ", ".join(
            _render_expression(value, boundary_names) for value in expression.arguments
        )
        suffix = "?" if expression.target in boundary_names else ""
        return f"__cw_native_{expression.target}({arguments}){suffix}"
    if isinstance(expression, CrateCallIR):
        arguments = ", ".join(
            _render_expression(value, boundary_names) for value in expression.arguments
        )
        return f"{'::'.join(expression.path)}({arguments})"
    if isinstance(expression, ConstructorIR):
        values = ", ".join(
            _render_expression(value, boundary_names) for value in expression.arguments
        )
        if expression.constructor == "String":
            return f"String::from({values})"
        if expression.constructor == "Vec":
            return f"vec![{values}]"
        if expression.constructor == "HashMap":
            return "std::collections::HashMap::new()"
        if expression.constructor == "Box":
            return f"Box::new({values})"
        if expression.constructor == "Rc":
            return f"std::rc::Rc::new({values})"
        if expression.constructor == "RefCell":
            return f"std::cell::RefCell::new({values})"
        if expression.constructor == "Arc":
            return f"std::sync::Arc::new({values})"
        if expression.constructor == "Mutex":
            return f"std::sync::Mutex::new({values})"
        if expression.constructor == "Channel":
            message_type = expression.type_ref.arguments[0].arguments[0].render()
            return f"std::sync::mpsc::channel::<{message_type}>()"
        if expression.constructor == "Spawn":
            return f"std::thread::spawn({values})"
        if expression.constructor == "BlockOn":
            return f"__cw_block_on({values})"
        if expression.constructor == "Join":
            return f"__cw_join2({values})"
        if expression.constructor == "Select":
            return f"__cw_select2({values})"
        if expression.constructor == "YieldNow":
            return "__cw_yield_now()"
        if expression.constructor == "SleepMillis":
            return f"__cw_sleep_millis({values})"
        if expression.constructor == "DynBox":
            return f"Box::new({values}) as {expression.type_ref.render()}"
        if expression.constructor == "ArrayRepeat":
            return f"[{values}; {expression.type_ref.const_value}]"
        if expression.constructor == "Some":
            return f"Some({values})"
        if expression.constructor == "None":
            return "None"
        if expression.constructor == "Ok":
            return f"Ok({values})"
        if expression.constructor == "Err":
            return f"Err({values})"
        if expression.constructor == "UnsafeRead":
            value = _render_expression(expression.arguments[0], boundary_names)
            return (
                "{ let __cw_pointer = &raw const "
                f"{value}; unsafe {{ *__cw_pointer }} }}"
            )
        if expression.constructor == "UnsafeWrite":
            target = _render_expression(expression.arguments[0], boundary_names)
            value = _render_expression(expression.arguments[1], boundary_names)
            return (
                "{ let __cw_pointer = &raw mut "
                f"{target}; unsafe {{ *__cw_pointer = {value}; }} }}"
            )
        if expression.constructor == "CAbs":
            value = _render_expression(expression.arguments[0], boundary_names)
            return (
                "{ let __cw_value: i32 = "
                f"{value}; if __cw_value == i32::MIN {{ "
                'panic!("C abs is undefined for i32::MIN"); } '
                "unsafe { __crabwalk_ffi::c_abs(__cw_value) } }"
            )
        if expression.constructor == "UnsafeStaticIncrement":
            value = _render_expression(expression.arguments[0], boundary_names)
            return (
                "{ static __CW_COUNTER: std::sync::atomic::AtomicU64 = "
                "std::sync::atomic::AtomicU64::new(0); "
                f"let __cw_amount: u64 = {value}; "
                "let __cw_previous = __CW_COUNTER.fetch_update("
                "std::sync::atomic::Ordering::Relaxed, "
                "std::sync::atomic::Ordering::Relaxed, "
                "|current| current.checked_add(__cw_amount))"
                '.expect("unsafe static counter overflow"); '
                "__cw_previous.checked_add(__cw_amount)"
                '.expect("unsafe static counter overflow") }'
            )
        if expression.constructor == "TypeAliasIdentity":
            value = _render_expression(expression.arguments[0], boundary_names)
            type_name = expression.type_ref.render()
            return (
                f"{{ type __CwAlias = {type_name}; "
                f"let __cw_value: __CwAlias = {value}; __cw_value }}"
            )
        if expression.constructor == "BoxedClosureCall":
            value = _render_expression(expression.arguments[0], boundary_names)
            addend = _render_expression(expression.arguments[1], boundary_names)
            return (
                "{ fn __cw_returns_closure(addend: u64) -> "
                "Box<dyn Fn(u64) -> u64> { Box::new(move |value| value + addend) } "
                f"__cw_returns_closure({addend})({value}) }}"
            )
        if expression.constructor == "ClosureVectorTotal":
            value = _render_expression(expression.arguments[0], boundary_names)
            return (
                "{ let __cw_callbacks: Vec<Box<dyn Fn(u64) -> u64>> = "
                "vec![Box::new(|item| item + 1), Box::new(|item| item * 2)]; "
                f"__cw_callbacks.iter().map(|callback| callback({value})).sum::<u64>() }}"
            )
        if expression.constructor == "TcpListener":
            address = _render_expression(expression.arguments[0], boundary_names)
            return f"std::net::TcpListener::bind({address}).unwrap()"
        if expression.constructor == "TcpStream":
            port = _render_expression(expression.arguments[0], boundary_names)
            return (
                "std::net::TcpStream::connect("
                f'format!("127.0.0.1:{{}}", {port})).unwrap()'
            )
        if expression.constructor == "ThreadPool":
            size = _render_expression(expression.arguments[0], boundary_names)
            return f"__CwThreadPool::new({size})"
    if isinstance(expression, StructConstructorIR):
        fields = ", ".join(
            f"{name}: {_render_expression(value, boundary_names)}"
            for name, value in expression.arguments
        )
        return f"{expression.struct_symbol} {{ {fields} }}"
    if isinstance(expression, EnumConstructorIR):
        values = ", ".join(
            _render_expression(value, boundary_names)
            for _, value in expression.arguments
        )
        if not expression.arguments:
            return f"{expression.enum_symbol}::{expression.variant}"
        if expression.tuple_style:
            return f"{expression.enum_symbol}::{expression.variant}({values})"
        fields = ", ".join(
            f"{name}: {_render_expression(value, boundary_names)}"
            for name, value in expression.arguments
        )
        return f"{expression.enum_symbol}::{expression.variant} {{ {fields} }}"
    if isinstance(expression, FieldAccessIR):
        rendered = (
            f"{_render_expression(expression.receiver, boundary_names)}."
            f"{expression.field}"
        )
        return rendered if _is_copy_type(expression.type_ref) else f"{rendered}.clone()"
    if isinstance(expression, MethodCallIR):
        rendered_receiver = _render_method_receiver(
            expression.receiver,
            boundary_names,
        )
        rendered_arguments = [
            _render_expression(value, boundary_names) for value in expression.arguments
        ]
        if expression.receiver.type_ref.rust_name == "Arc":
            if expression.method == "strong_count":
                return f"std::sync::Arc::strong_count(&{rendered_receiver})"
            if expression.method == "add_locked":
                return (
                    f"{{ *{rendered_receiver}.lock().unwrap() += "
                    f"{rendered_arguments[0]}; }}"
                )
            if expression.method == "get_locked":
                return f"*{rendered_receiver}.lock().unwrap()"
        if expression.receiver.type_ref.rust_name == "Box":
            if expression.method == "deref_copy":
                return f"*{rendered_receiver}"
        if expression.receiver.type_ref.rust_name == "Rc":
            if expression.method == "strong_count":
                return f"std::rc::Rc::strong_count(&{rendered_receiver})"
            if expression.method == "deref_copy":
                return f"*{rendered_receiver}"
        if expression.receiver.type_ref.rust_name == "RefCell":
            if expression.method == "borrow_copy":
                return f"*{rendered_receiver}.borrow()"
        if expression.receiver.type_ref.rust_name == "Sender":
            if expression.method == "send":
                return f"{rendered_receiver}.send({rendered_arguments[0]}).unwrap()"
        if expression.receiver.type_ref.rust_name == "Receiver":
            if expression.method == "recv":
                return f"{rendered_receiver}.recv().unwrap()"
            if expression.method == "recv_async":
                return f"__cw_recv_async(&{rendered_receiver})"
        if expression.receiver.type_ref.rust_name == "ThreadHandle":
            if expression.method == "join":
                return f"{rendered_receiver}.join().unwrap()"
        if expression.receiver.type_ref.rust_name == "TcpListener":
            if expression.method == "local_port":
                return f"u64::from({rendered_receiver}.local_addr().unwrap().port())"
            if expression.method == "serve_http_once":
                hello, missing = rendered_arguments
                return (
                    "{ let (mut __cw_stream, _) = "
                    f"{rendered_receiver}.accept().unwrap(); "
                    "let mut __cw_request = String::new(); "
                    "std::io::Read::read_to_string(&mut __cw_stream, "
                    "&mut __cw_request).unwrap(); "
                    "let (__cw_status, __cw_body, __cw_code) = "
                    'if __cw_request.starts_with("GET / HTTP/1.1\\r\\n") { '
                    f'("HTTP/1.1 200 OK", {hello}, 200u64) '
                    '} else if __cw_request.starts_with("GET /sleep HTTP/1.1\\r\\n") { '
                    "std::thread::sleep(std::time::Duration::from_millis(50)); "
                    f'("HTTP/1.1 200 OK", {hello}, 200u64) '
                    f'}} else {{ ("HTTP/1.1 404 NOT FOUND", {missing}, 404u64) }}; '
                    "let __cw_response = format!("
                    '"{}\\r\\nContent-Length: {}\\r\\nConnection: close\\r\\n\\r\\n{}", '
                    "__cw_status, __cw_body.len(), __cw_body); "
                    "std::io::Write::write_all(&mut __cw_stream, "
                    "__cw_response.as_bytes()).unwrap(); "
                    "std::io::Write::flush(&mut __cw_stream).unwrap(); "
                    "__cw_stream.shutdown(std::net::Shutdown::Both).unwrap(); "
                    "__cw_code }"
                )
        if expression.receiver.type_ref.rust_name == "TcpStream":
            if expression.method == "write_get":
                path = rendered_arguments[0]
                return (
                    "{ let __cw_request = format!("
                    '"GET {} HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n", '
                    f"{path}); std::io::Write::write_all(&mut {rendered_receiver}, "
                    "__cw_request.as_bytes()).unwrap(); }"
                )
            if expression.method == "shutdown_write":
                return (
                    f"{rendered_receiver}.shutdown(std::net::Shutdown::Write).unwrap()"
                )
            if expression.method == "read_to_string":
                return (
                    "{ let mut __cw_response = String::new(); "
                    f"std::io::Read::read_to_string(&mut {rendered_receiver}, "
                    "&mut __cw_response).unwrap(); __cw_response }"
                )
        if expression.receiver.type_ref.rust_name == "HashMap":
            if expression.method in {"contains_key", "remove"}:
                return (
                    f"{rendered_receiver}.{expression.method}(&{rendered_arguments[0]})"
                )
            if expression.method == "get_or":
                return (
                    f"{rendered_receiver}.get(&{rendered_arguments[0]})"
                    f".cloned().unwrap_or({rendered_arguments[1]})"
                )
            if expression.method == "entry_or_insert":
                return (
                    f"{rendered_receiver}.entry({rendered_arguments[0]})"
                    f".or_insert({rendered_arguments[1]}).clone()"
                )
            if expression.method == "add":
                return (
                    "{ *"
                    f"{rendered_receiver}.entry({rendered_arguments[0]})"
                    f".or_insert(0) += {rendered_arguments[1]}; }}"
                )
        if (
            expression.receiver.type_ref.rust_name == "Vec"
            and expression.method == "iter"
        ):
            return f"{rendered_receiver}.iter().copied()"
        if (
            expression.receiver.type_ref.rust_name == "Vec"
            and expression.method == "iter_ref"
        ):
            return f"{rendered_receiver}.iter()"
        if (
            expression.receiver.type_ref.rust_name == "Vec"
            and expression.method == "split_at_mut_sum"
        ):
            midpoint = rendered_arguments[0]
            element = expression.receiver.type_ref.arguments[0].render()
            return (
                f"{{ let __cw_mid: usize = {midpoint}; "
                f"let __cw_len = {rendered_receiver}.len(); "
                'assert!(__cw_mid <= __cw_len, "midpoint out of bounds"); '
                f"let __cw_pointer = {rendered_receiver}.as_mut_ptr(); "
                "let (__cw_left, __cw_right) = unsafe { "
                "(std::slice::from_raw_parts_mut(__cw_pointer, __cw_mid), "
                "std::slice::from_raw_parts_mut(__cw_pointer.add(__cw_mid), "
                "__cw_len - __cw_mid)) }; "
                f"__cw_left.iter().copied().sum::<{element}>() + "
                f"__cw_right.iter().copied().sum::<{element}>() }}"
            )
        if expression.receiver.type_ref.rust_name == "Iterator":
            if expression.method == "collect_vec":
                return f"{rendered_receiver}.collect::<Vec<_>>()"
        arguments = ", ".join(rendered_arguments)
        return f"{rendered_receiver}.{expression.method}({arguments})"
    if isinstance(expression, TraitCallIR):
        receiver = _render_expression(expression.receiver, boundary_names)
        return (
            f"<{expression.concrete_type.render()} as "
            f"{expression.trait_symbol}>::{expression.method}(&{receiver})"
        )
    if isinstance(expression, FunctionPointerTwiceIR):
        argument = _render_expression(expression.argument, boundary_names)
        parameter = expression.parameter_type.render()
        result = expression.type_ref.render()
        return (
            f"{{ let __cw_operation: fn({parameter}) -> {result} = "
            f"__cw_native_{expression.target}; "
            f"let __cw_argument: {parameter} = {argument}; "
            "__cw_operation(__cw_argument) + __cw_operation(__cw_argument) }"
        )
    if isinstance(expression, NativePrintlnIR):
        return (
            f'println!("{{}}", {_render_expression(expression.value, boundary_names)})'
        )
    if isinstance(expression, PythonPrintIR):
        value = _render_expression(expression.value, boundary_names)
        if expression.value.type_ref.rust_name == "String":
            value = f"{value}.clone()"
        return (
            "Python::attach(|py| -> PyResult<()> { "
            'py.import("builtins")?.getattr("print")?.call1(('
            f"{value},))?; Ok(()) }})?"
        )
    if isinstance(expression, TryIR):
        return f"{_render_expression(expression.value, boundary_names)}?"
    if isinstance(expression, AwaitIR):
        return f"{_render_expression(expression.value, boundary_names)}.await"
    if isinstance(expression, PanicIR):
        return (
            f'panic!("{{}}", {_render_expression(expression.message, boundary_names)})'
        )
    if isinstance(expression, ClosureIR):
        body = _render_expression(expression.body, boundary_names)
        if expression.parameter is None:
            return f"move || {body}"
        if expression.borrowed_parameter:
            return f"|__cw_item| {{ let {expression.parameter} = *__cw_item; {body} }}"
        return f"|{expression.parameter}| {body}"
    raise AssertionError(f"unhandled expression IR: {type(expression).__name__}")


def _render_method_receiver(
    expression: ExpressionIR,
    boundary_names: set[str],
) -> str:
    """Render a borrowed method receiver without cloning an owned struct field."""

    if isinstance(expression, (FieldAccessIR, IndexIR)):
        return _render_place_expression(expression, boundary_names)
    return _render_expression(expression, boundary_names)


def _render_place_expression(
    expression: ExpressionIR,
    boundary_names: set[str],
) -> str:
    """Render a storage place without cloning an intermediate projection."""

    if isinstance(expression, NameIR):
        return expression.name
    if isinstance(expression, FieldAccessIR):
        return (
            f"{_render_place_expression(expression.receiver, boundary_names)}."
            f"{expression.field}"
        )
    if isinstance(expression, IndexIR):
        receiver = _render_place_expression(expression.receiver, boundary_names)
        index = _render_expression(expression.index, boundary_names)
        return f"{receiver}[{index}]"
    return _render_expression(expression, boundary_names)


def _ends_with_return(statements: tuple[StatementIR, ...]) -> bool:
    return bool(statements) and isinstance(statements[-1], ReturnIR)


def _is_copy_type(type_ref: TypeRef) -> bool:
    return (
        type_ref.is_numeric
        or type_ref.rust_name in {"bool", "char"}
        or type_ref.rust_name == "Unit"
        or (
            type_ref.rust_name in {"Tuple", "Array"}
            and all(_is_copy_type(value) for value in type_ref.arguments)
        )
    )


def _rust_string_literal(value: str) -> str:
    pieces = ['"']
    for character in value:
        code = ord(character)
        if character == '"':
            pieces.append('\\"')
        elif character == "\\":
            pieces.append("\\\\")
        elif character == "\n":
            pieces.append("\\n")
        elif character == "\r":
            pieces.append("\\r")
        elif character == "\t":
            pieces.append("\\t")
        elif code < 0x20 or code == 0x7F:
            pieces.append(f"\\u{{{code:x}}}")
        else:
            pieces.append(character)
    pieces.append('"')
    return "".join(pieces)


def _rust_char_literal(value: str) -> str:
    character = value[0]
    escapes = {
        "'": "\\'",
        "\\": "\\\\",
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
        "\0": "\\0",
    }
    escaped = escapes.get(character)
    if escaped is None:
        code = ord(character)
        escaped = f"\\u{{{code:x}}}" if code < 0x20 or code == 0x7F else character
    return f"'{escaped}'"


def _cargo_dependencies(ir: PackageIR) -> str:
    lines: list[str] = []
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        cargo_key = cargo_dependency_key(dependency.package, dependency.binding)
        fields: list[str] = []
        if cargo_key != dependency.package:
            fields.append(f"package = {_toml_string(dependency.package)}")
        if dependency.version is not None:
            fields.append(f"version = {_toml_string(dependency.version)}")
        if dependency.path is not None:
            fields.append(f"path = {_toml_string(Path(dependency.path).as_posix())}")
        if dependency.git is not None:
            fields.append(f"git = {_toml_string(dependency.git)}")
        if dependency.rev is not None:
            fields.append(f"rev = {_toml_string(dependency.rev)}")
        if dependency.features:
            features = ", ".join(_toml_string(value) for value in dependency.features)
            fields.append(f"features = [{features}]")
        lines.append(f"{cargo_key} = {{ {', '.join(fields)} }}")
    return "\n".join(lines)


def cargo_dependency_specification(ir: PackageIR) -> dict[str, object]:
    """Return every generated Cargo dependency input in fingerprintable form."""

    return {
        "mandatory": [
            {
                "binding": PYO3_CARGO_ALIAS,
                "package": "pyo3",
                "version": f"={PYO3_VERSION}",
                "features": ["extension-module"],
            }
        ],
        "mandatory_build": [
            {
                "package": "pyo3-build-config",
                "version": f"={PYO3_VERSION}",
            }
        ],
        "declared": [
            {
                "binding": crate.binding,
                "cargo_key": cargo_dependency_key(crate.package, crate.binding),
                "package": crate.package,
                "version": crate.version,
                "features": list(crate.features),
                "path": crate.path,
                "git": crate.git,
                "rev": crate.rev,
            }
            for crate in sorted(ir.crates, key=lambda value: value.binding)
        ],
    }


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _owned_vector_types(ir: PackageIR) -> tuple[TypeRef, ...]:
    values: dict[str, TypeRef] = {}
    for function in ir.functions:
        if not function.exported:
            continue
        for parameter in function.parameters:
            if (
                parameter.type_ref.ownership is not None
                and parameter.type_ref.underlying.rust_name == "Vec"
            ):
                vector = parameter.type_ref.underlying
                values[vector.render()] = vector
    return tuple(values[key] for key in sorted(values))


def _write_owned_vector_class(writer: _Writer, vector_type: TypeRef) -> None:
    python_name, rust_name = owned_class_names(vector_type)
    rendered = vector_type.render()
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{rendered}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("#[new]")
    writer.line(f"fn new(value: {rendered}) -> Self {{")
    writer.enter()
    writer.line("Self { value: Some(value) }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __len__(&self) -> PyResult<usize> {")
    writer.enter()
    writer.line("self.value.as_ref().map(|value| value.len()).ok_or_else(|| {")
    writer.enter()
    writer.line(
        f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
    )
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(f"fn to_python(&self) -> PyResult<{rendered}> {{")
    writer.enter()
    writer.line("self.value.as_ref().cloned().ok_or_else(|| {")
    writer.enter()
    writer.line(
        f'{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("CrabwalkMoveError: value was moved")'
    )
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(f'Some(value) => format!("{python_name}({{:?}})", value),')
    writer.line(f'None => String::from("{python_name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _wrapper_parameter(parameter: ParameterIR) -> str:
    ownership = parameter.type_ref.ownership
    if ownership is None:
        return f"{parameter.name}: {parameter.type_ref.render()}"
    vector = parameter.type_ref.underlying
    _, rust_class = owned_class_names(vector)
    if ownership == "Ref":
        return f"{parameter.name}: PyRef<'_, {rust_class}>"
    return f"mut {parameter.name}: PyRefMut<'_, {rust_class}>"


def _write_wrapper_extraction(writer: _Writer, parameter: ParameterIR) -> None:
    ownership = parameter.type_ref.ownership
    if ownership is None:
        return
    access = {
        "Owned": "take()",
        "Ref": "as_ref()",
        "Mut": "as_mut()",
    }[ownership]
    writer.line(
        (
            f"let __cw_arg_{parameter.name} = "
            f"{parameter.name}.value.{access}.ok_or_else(|| "
            f"{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError::new_err("
            f'"CrabwalkMoveError: {parameter.name} was moved"))?;'
        ),
        parameter.span,
        "ownership_boundary",
    )
