"""Deterministic Rust and Cargo generation from semantic IR."""

from __future__ import annotations

import json
from dataclasses import dataclass

from crabwalk.native_exceptions import (
    NATIVE_BORROW_ERROR,
    NATIVE_MOVE_ERROR,
    NATIVE_PANIC_ERROR,
    NATIVE_RUST_RESULT_ERROR,
)

from .ir import (
    Effect,
    EnumIR,
    FunctionIR,
    PackageIR,
    ParameterIR,
    StructFieldIR,
    StructIR,
    TraitIR,
    TypeRef,
)
from .cargo_emission import render_build_rs, render_cargo_toml
from .emission import EmissionNames, Writer as _Writer
from .rust_emission import write_native_function as _write_native_function
from .naming import PYO3_CARGO_ALIAS, cargo_dependency_key, owned_class_names

CODEGEN_SCHEMA_VERSION = 36

_NATIVE_EXCEPTION_TYPES = (
    (NATIVE_MOVE_ERROR, "__CwNativeMoveError"),
    (NATIVE_BORROW_ERROR, "__CwNativeBorrowError"),
    (NATIVE_PANIC_ERROR, "__CwNativePanicError"),
    (NATIVE_RUST_RESULT_ERROR, "__CwNativeRustResultError"),
)


@dataclass(frozen=True, slots=True)
class GeneratedProject:
    cargo_toml: str
    build_rs: str
    rust_source: str
    source_map: dict[str, object]
    ir_json: str


def generate_project(ir: PackageIR, extension_name: str) -> GeneratedProject:
    from .validation import validate_package_ir

    validate_package_ir(ir)
    writer = _Writer()
    domains_by_symbol = {value.symbol: value.type_ref for value in ir.structs}
    domains_by_symbol.update({value.symbol: value.type_ref for value in ir.enums})
    boundary_names = {
        function.rust_symbol for function in ir.functions if function.python_boundary
    }
    writer.line("// Generated by Crabwalk. Inspectable; do not edit.")
    writer.line(
        f"// IR schema: {ir.schema_version}; codegen schema: {CODEGEN_SCHEMA_VERSION}"
    )
    writer.line(f"extern crate {PYO3_CARGO_ALIAS} as pyo3;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        cargo_key = cargo_dependency_key(dependency.package, dependency.binding)
        writer.line(f"extern crate {cargo_key} as {dependency.binding};")
    writer.line(f"use {PYO3_CARGO_ALIAS}::prelude::*;")
    if any(_enum_has_heterogeneous_fields(value) for value in ir.enums):
        writer.line(f"use {PYO3_CARGO_ALIAS}::IntoPyObjectExt;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        if dependency.package == "rayon":
            writer.line(f"use {dependency.binding}::prelude::*;")
    writer.line("mod __crabwalk_ffi {")
    writer.enter()
    writer.line('unsafe extern "C" {')
    writer.enter()
    writer.line('#[link_name = "abs"]')
    writer.line("pub(super) fn c_abs(input: i32) -> i32;")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    _write_native_exceptions(writer)
    writer.line()
    _write_panic_boundary(writer)
    writer.line()
    _write_thread_pool(writer)
    writer.line()

    if any(function.is_async for function in ir.functions):
        _write_block_on_executor(writer)
        writer.line()

    for trait in ir.traits:
        _write_native_trait(writer, trait)
        writer.line()

    for enum in ir.enums:
        _write_native_enum(writer, enum)
        writer.line()
        _write_owned_enum_class(writer, enum, domains_by_symbol)
        writer.line()

    for struct in ir.structs:
        _write_native_struct(writer, struct)
        writer.line()
        _write_owned_struct_class(writer, struct, domains_by_symbol)
        writer.line()

    owned_vectors = _owned_vector_types(ir)
    for vector_type in owned_vectors:
        _write_owned_vector_class(writer, vector_type, domains_by_symbol)
        writer.line()

    for function in ir.functions:
        _write_native_function(writer, function, boundary_names)
        writer.line()

    _write_method_impls(writer, ir)

    for function in ir.functions:
        if function.exported:
            _write_export_wrapper(writer, function, boundary_names)
            writer.line()

    writer.line(f'#[pymodule(name = "{extension_name}")]')
    writer.line("fn __crabwalk_module(m: &Bound<'_, PyModule>) -> PyResult<()> {")
    writer.enter()
    for python_name, rust_name in _NATIVE_EXCEPTION_TYPES:
        writer.line(f'm.add("{python_name}", m.py().get_type::<{rust_name}>())?;')
    for function in ir.functions:
        if not function.exported:
            continue
        writer.line(
            f"m.add_function({PYO3_CARGO_ALIAS}::wrap_pyfunction!({function.rust_symbol}, m)?)?;",
            function.span,
            "abi_export",
        )
    for vector_type in owned_vectors:
        _, rust_class = owned_class_names(vector_type)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for struct in ir.structs:
        _, rust_class = owned_class_names(struct.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for enum in ir.enums:
        _, rust_class = owned_class_names(enum.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    writer.line("std::result::Result::Ok(())")
    writer.leave()
    writer.line("}")

    source_map = {
        "schema_version": 2,
        "generated_file": "src/lib.rs",
        "source_hash": ir.source_hash,
        "compiler_input_hash": ir.compiler_input_hash,
        "wheel_source_integrity_hash": ir.wheel_source_integrity_hash,
        "entries": writer.mappings,
    }
    return GeneratedProject(
        cargo_toml=render_cargo_toml(ir, extension_name),
        build_rs=render_build_rs(extension_name),
        rust_source=writer.render(),
        source_map=source_map,
        ir_json=json.dumps(ir.to_dict(), indent=2, sort_keys=True) + "\n",
    )


def _write_native_struct(writer: _Writer, struct: StructIR) -> None:
    derives = ["Clone", "Debug"] + ["::".join(value) for value in struct.derives]
    writer.line(f"#[derive({', '.join(derives)})]", struct.span, "struct_derive")
    writer.line(f"struct {struct.symbol} {{", struct.span, "struct")
    writer.enter()
    for field in struct.fields:
        writer.line(
            f"pub {field.rust_name}: {field.type_ref.render()},",
            field.span,
            "struct_field",
        )
    writer.leave()
    writer.line("}")


def _write_native_trait(writer: _Writer, trait: TraitIR) -> None:
    writer.line(f"trait {trait.symbol} {{", trait.span, "trait")
    writer.enter()
    for method in trait.methods:
        writer.line(
            f"fn {method.rust_name}(&self) -> {method.return_type.render()};",
            method.span,
            "trait_method",
        )
    writer.leave()
    writer.line("}")


def _write_method_impls(writer: _Writer, package: PackageIR) -> None:
    trait_method_names = {
        (trait.symbol, method.name): method.rust_name
        for trait in package.traits
        for method in trait.methods
    }
    inherent = [
        function
        for function in package.functions
        if function.method_for is not None
        and function.trait_symbol is None
        and function.operator_kind is None
    ]
    for function in inherent:
        assert function.method_for is not None and function.method_name is not None
        writer.line(f"impl {function.method_for.render()} {{")
        writer.enter()
        _write_method_glue(writer, function)
        writer.leave()
        writer.line("}")
        writer.line()

    operators = [
        function
        for function in package.functions
        if function.method_for is not None and function.operator_kind is not None
    ]
    for function in operators:
        assert function.method_for is not None
        assert function.operator_kind == "add"
        assert len(function.parameters) == 2
        right = function.parameters[1]
        writer.line(
            f"impl std::ops::Add<{right.type_ref.render()}> "
            f"for {function.method_for.render()} {{"
        )
        writer.enter()
        writer.line(f"type Output = {function.return_type.render()};")
        writer.line()
        writer.line(
            f"fn add(self, {right.rust_name}: {right.type_ref.render()}) -> Self::Output {{",
            function.span,
            "operator_impl",
        )
        writer.enter()
        writer.line(f"__cw_native_{function.rust_symbol}(self, {right.rust_name})")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
        writer.line()

    trait_groups: dict[tuple[str, str], list[FunctionIR]] = {}
    for function in package.functions:
        if function.method_for is None or function.trait_symbol is None:
            continue
        trait_groups.setdefault(
            (function.trait_symbol, function.method_for.rust_name), []
        ).append(function)
    for (trait_symbol, _), functions in trait_groups.items():
        target = functions[0].method_for
        assert target is not None
        writer.line(f"impl {trait_symbol} for {target.render()} {{")
        writer.enter()
        for function in functions:
            assert function.method_name is not None
            _write_method_glue(
                writer,
                function,
                trait_method_names[(trait_symbol, function.method_name)],
            )
        writer.leave()
        writer.line("}")
        writer.line()


def _write_method_glue(
    writer: _Writer,
    function: FunctionIR,
    emitted_method_name: str | None = None,
) -> None:
    assert function.method_name is not None and function.parameters
    receiver_type = function.parameters[0].type_ref
    receiver = {
        "Ref": "&self",
        "Mut": "&mut self",
        "Owned": "self",
    }[receiver_type.rust_name]
    tail = [
        f"{parameter.rust_name}: {parameter.type_ref.render()}"
        for parameter in function.parameters[1:]
    ]
    parameters = ", ".join((receiver, *tail))
    arguments = ", ".join(
        ("self", *(parameter.rust_name for parameter in function.parameters[1:]))
    )
    writer.line(
        f"fn {emitted_method_name or function.method_name}({parameters}) "
        f"-> {function.return_type.render()} {{",
        function.span,
        "method_impl",
    )
    writer.enter()
    writer.line(f"__cw_native_{function.rust_symbol}({arguments})")
    writer.leave()
    writer.line("}")


def _write_native_enum(writer: _Writer, enum: EnumIR) -> None:
    derives = ["Clone", "Debug"] + ["::".join(value) for value in enum.derives]
    writer.line(f"#[derive({', '.join(derives)})]", enum.span, "enum_derive")
    writer.line(f"enum {enum.symbol} {{", enum.span, "enum")
    writer.enter()
    for variant in enum.variants:
        if not variant.fields:
            writer.line(f"{variant.rust_name},", variant.span, "enum_variant")
        elif variant.tuple_style:
            fields = ", ".join(field.type_ref.render() for field in variant.fields)
            writer.line(f"{variant.rust_name}({fields}),", variant.span, "enum_variant")
        else:
            writer.line(f"{variant.rust_name} {{", variant.span, "enum_variant")
            writer.enter()
            for field in variant.fields:
                writer.line(
                    f"{field.rust_name}: {field.type_ref.render()},",
                    field.span,
                    "enum_field",
                )
            writer.leave()
            writer.line("},")
    writer.leave()
    writer.line("}")


def _write_owned_enum_class(
    writer: _Writer,
    enum: EnumIR,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(enum.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{enum.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line("#[allow(non_snake_case)]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()

    def domain_class(type_ref: TypeRef) -> str | None:
        domain = domains_by_symbol.get(type_ref.rust_name)
        return owned_class_names(domain)[1] if domain is not None else None

    for variant in enum.variants:
        constructor_names = EmissionNames.reserving(
            *(field.rust_name for field in variant.fields)
        )
        extracted_fields: dict[str, str] = {}
        parameters = ", ".join(
            (
                f"{field.rust_name}: PyRef<'_, {domain_class(field.type_ref)}>"
                if domain_class(field.type_ref) is not None
                else f"{field.rust_name}: {field.type_ref.render()}"
            )
            for field in variant.fields
        )
        fallible = any(domain_class(field.type_ref) for field in variant.fields)
        writer.line("#[staticmethod]")
        return_type = "PyResult<Self>" if fallible else "Self"
        if variant.rust_name != variant.name:
            writer.line(f'#[pyo3(name = "{variant.name}")]')
        writer.line(f"fn {variant.rust_name}({parameters}) -> {return_type} {{")
        writer.enter()
        for field in variant.fields:
            if domain_class(field.type_ref) is None:
                continue
            extracted_field = constructor_names.temporary(f"field_{field.name}")
            extracted_fields[field.name] = extracted_field
            writer.line(
                f"let {extracted_field} = "
                f"{field.rust_name}.value.as_ref().ok_or_else(|| {{"
            )
            writer.enter()
            writer.line(_native_move_error(field.name))
            writer.leave()
            writer.line("})?.clone();")
        if not variant.fields:
            value = f"{enum.symbol}::{variant.rust_name}"
        elif variant.tuple_style:
            arguments = ", ".join(
                (
                    extracted_fields[field.name]
                    if domain_class(field.type_ref) is not None
                    else field.rust_name
                )
                for field in variant.fields
            )
            value = f"{enum.symbol}::{variant.rust_name}({arguments})"
        else:
            arguments = ", ".join(
                (
                    f"{field.rust_name}: {extracted_fields[field.name]}"
                    if domain_class(field.type_ref) is not None
                    else f"{field.rust_name}: {field.rust_name}"
                )
                for field in variant.fields
            )
            value = f"{enum.symbol}::{variant.rust_name} {{ {arguments} }}"
        wrapped = f"Self {{ value: std::option::Option::Some({value}) }}"
        writer.line(f"std::result::Result::Ok({wrapped})" if fallible else wrapped)
        writer.leave()
        writer.line("}")
        writer.line()
    writer.line("fn variant(&self) -> PyResult<&'static str> {")
    writer.enter()
    writer.line("match self.value.as_ref() {")
    writer.enter()
    for variant in enum.variants:
        pattern = _enum_variant_pattern(enum, variant.name, (), variant.tuple_style)
        writer.line(
            f"std::option::Option::Some({pattern}) => "
            f'std::result::Result::Ok("{variant.name}"),'
        )
    writer.line(
        f"std::option::Option::None => std::result::Result::Err("
        f"{_native_move_error('')}),"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    for field_name, candidate_types in sorted(field_types.items()):
        heterogeneous = len(candidate_types) > 1
        field_type = next(iter(candidate_types))
        nested_class = domain_class(field_type) if not heterogeneous else None
        getter_names = EmissionNames.reserving("self", "py")
        stored_value = getter_names.temporary("stored_value")
        target_name = getter_names.temporary("variant_target")
        getter_field = next(
            field
            for variant in enum.variants
            for field in variant.fields
            if field.name == field_name
        )
        writer.line()
        writer.line(f'#[getter("{field_name}")]')
        if heterogeneous:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self, py: Python<'_>) -> "
                "PyResult<Option<Py<PyAny>>> {"
            )
        elif nested_class is not None:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self, py: Python<'_>) -> "
                f"PyResult<Option<Py<{nested_class}>>> {{"
            )
        else:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self) "
                f"-> PyResult<Option<{field_type.render()}>> {{"
            )
        writer.enter()
        writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"match {stored_value} {{")
        writer.enter()
        for variant in enum.variants:
            target = next(
                (field for field in variant.fields if field.name == field_name), None
            )
            if target is None:
                continue
            bindings = tuple(
                (field.name, target_name if field.name == field_name else "")
                for field in variant.fields
            )
            pattern = _enum_variant_pattern(
                enum,
                variant.name,
                bindings,
                variant.tuple_style,
            )
            target_class = domain_class(target.type_ref)
            if target_class is not None:
                native = (
                    f"Py::new(py, {target_class} {{ value: "
                    f"std::option::Option::Some({target_name}.clone()) }})?"
                )
                converted = f"{native}.into_any()" if heterogeneous else native
            else:
                converted = (
                    f"{target_name}.clone().into_py_any(py)?"
                    if heterogeneous
                    else f"{target_name}.clone()"
                )
            writer.line(
                f"{pattern} => std::result::Result::Ok("
                f"std::option::Option::Some({converted})),"
            )
        writer.line("_ => std::result::Result::Ok(std::option::Option::None),")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{enum.name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{enum.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _enum_has_heterogeneous_fields(enum: EnumIR) -> bool:
    """Return whether one Python-visible payload name has multiple Rust types.

    Rust tuple variants conventionally reuse positional names such as ``_0`` even
    though each variant is free to choose an unrelated payload type. PyO3 needs a
    single return type for a Python property, so those getters erase only the ABI
    representation to ``PyAny`` while the native enum remains fully typed.
    """

    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    return any(len(value) > 1 for value in field_types.values())


def _enum_variant_pattern(
    enum: EnumIR,
    variant_name: str,
    bindings: tuple[tuple[str, str], ...],
    tuple_style: bool,
) -> str:
    variant = next(value for value in enum.variants if value.name == variant_name)
    if not variant.fields:
        return f"{enum.symbol}::{variant.rust_name}"
    values = {field: local for field, local in bindings}
    if tuple_style:
        patterns = ", ".join(values.get(field.name) or "_" for field in variant.fields)
        return f"{enum.symbol}::{variant.rust_name}({patterns})"
    patterns = ", ".join(
        f"{field.rust_name}: {values.get(field.name) or '_'}"
        for field in variant.fields
    )
    return f"{enum.symbol}::{variant.rust_name} {{ {patterns} }}"


def _write_owned_struct_class(
    writer: _Writer,
    struct: StructIR,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(struct.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{struct.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()

    def domain_class(field: StructFieldIR) -> str | None:
        domain = domains_by_symbol.get(field.type_ref.rust_name)
        return owned_class_names(domain)[1] if domain is not None else None

    parameters = ", ".join(
        (
            f"{field.rust_name}: PyRef<'_, {domain_class(field)}>"
            if domain_class(field) is not None
            else f"{field.rust_name}: {field.type_ref.render()}"
        )
        for field in struct.fields
    )
    writer.line("#[new]")
    writer.line(f"fn new({parameters}) -> PyResult<Self> {{")
    writer.enter()
    constructor_names = EmissionNames.reserving(
        *(field.rust_name for field in struct.fields)
    )
    extracted_fields: dict[str, str] = {}
    for field in struct.fields:
        if domain_class(field) is None:
            continue
        extracted_field = constructor_names.temporary(f"field_{field.name}")
        extracted_fields[field.name] = extracted_field
        writer.line(
            f"let {extracted_field} = {field.rust_name}.value.as_ref().ok_or_else(|| {{"
        )
        writer.enter()
        writer.line(_native_move_error(field.name))
        writer.leave()
        writer.line("})?.clone();")
    writer.line(
        "std::result::Result::Ok(Self { value: std::option::Option::Some("
        + struct.symbol
        + " {"
    )
    writer.enter()
    for field in struct.fields:
        value = (
            extracted_fields[field.name]
            if domain_class(field) is not None
            else field.rust_name
        )
        writer.line(f"{field.rust_name}: {value},")
    writer.leave()
    writer.line("}) })")
    writer.leave()
    writer.line("}")
    for field in struct.fields:
        nested_class = domain_class(field)
        getter_names = EmissionNames.reserving("self", "py")
        stored_value = getter_names.temporary("stored_value")
        writer.line()
        writer.line(f'#[getter("{field.name}")]')
        if nested_class is None:
            writer.line(
                f"fn get_{field.rust_name}(&self) "
                f"-> PyResult<{field.type_ref.render()}> {{"
            )
        else:
            writer.line(
                f"fn get_{field.rust_name}(&self, py: Python<'_>) -> "
                f"PyResult<Py<{nested_class}>> {{"
            )
        writer.enter()
        writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        if nested_class is None:
            writer.line(
                f"std::result::Result::Ok({stored_value}.{field.rust_name}.clone())"
            )
        else:
            writer.line(
                f"Py::new(py, {nested_class} {{ value: std::option::Option::Some("
                f"{stored_value}.{field.rust_name}.clone()) }})"
            )
        writer.leave()
        writer.line("}")
        writer.line()
        writer.line(f'#[setter("{field.name}")]')
        setter_type = (
            f"PyRef<'_, {nested_class}>"
            if nested_class is not None
            else field.type_ref.render()
        )
        writer.line(
            f"fn set_{field.rust_name}(&mut self, value: {setter_type}) "
            "-> PyResult<()> {"
        )
        writer.enter()
        setter_names = EmissionNames.reserving("self", "value")
        assigned_value = "value"
        if nested_class is not None:
            assigned_value = setter_names.temporary("assigned_value")
            writer.line(f"let {assigned_value} = value.value.as_ref().ok_or_else(|| {{")
            writer.enter()
            writer.line(_native_move_error(field.name))
            writer.leave()
            writer.line("})?.clone();")
        target = setter_names.temporary("target")
        writer.line(f"let {target} = self.value.as_mut().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"{target}.{field.rust_name} = {assigned_value};")
        writer.line("std::result::Result::Ok(())")
        writer.leave()
        writer.line("}")
    writer.line()
    tuple_types = ", ".join(
        (
            f"Py<{domain_class(field)}>"
            if domain_class(field) is not None
            else field.type_ref.render()
        )
        for field in struct.fields
    )
    if len(struct.fields) == 1:
        tuple_types += ","
    python_parameter = (
        ", py: Python<'_>"
        if any(domain_class(field) for field in struct.fields)
        else ""
    )
    writer.line(
        f"fn to_python(&self{python_parameter}) -> PyResult<({tuple_types})> {{"
    )
    writer.enter()
    to_python_names = EmissionNames.reserving("self", "py")
    stored_value = to_python_names.temporary("stored_value")
    tuple_values = ", ".join(
        (
            f"Py::new(py, {domain_class(field)} {{ value: "
            f"std::option::Option::Some({stored_value}.{field.rust_name}.clone()) }})?"
            if domain_class(field) is not None
            else f"{stored_value}.{field.rust_name}.clone()"
        )
        for field in struct.fields
    )
    if len(struct.fields) == 1:
        tuple_values += ","
    writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})?;")
    writer.line(f"std::result::Result::Ok(({tuple_values}))")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{struct.name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{struct.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_export_wrapper(
    writer: _Writer,
    function: FunctionIR,
    boundary_names: set[str],
) -> None:
    emission_names = EmissionNames.for_function(function)
    wrapper_parameters = [
        _wrapper_parameter(parameter) for parameter in function.parameters
    ]
    releases_gil = function_releases_gil(function)
    python_token = emission_names.temporary("python_token") if releases_gil else None
    if releases_gil:
        assert python_token is not None
        wrapper_parameters.insert(0, f"{python_token}: Python<'_>")
    parameters = ", ".join(wrapper_parameters)
    extracted_arguments = {
        parameter.rust_name: emission_names.temporary(f"argument_{parameter.name}")
        for parameter in function.parameters
        if parameter.type_ref.ownership is not None
    }
    arguments = ", ".join(
        (
            extracted_arguments[parameter.rust_name]
            if parameter.type_ref.ownership is not None
            else parameter.rust_name
        )
        for parameter in function.parameters
    )
    writer.line("#[pyfunction]")
    owned_return = function.return_type.ownership == "Owned"
    if owned_return:
        _, return_class = owned_class_names(function.return_type.underlying)
        wrapper_return = f"PyResult<{return_class}>"
    else:
        wrapper_return = (
            f"PyResult<{function.return_type.arguments[0].render()}>"
            if function.return_type.rust_name == "Result"
            else f"PyResult<{function.return_type.render()}>"
        )
    writer.line(
        f"fn {function.rust_symbol}({parameters}) -> {wrapper_return} {{",
        function.span,
        "abi_wrapper",
    )
    writer.enter()
    for parameter in function.parameters:
        _write_wrapper_ownership_preflight(writer, parameter)
    for parameter in function.parameters:
        _write_wrapper_extraction(
            writer,
            parameter,
            extracted_arguments.get(parameter.rust_name),
        )
    if owned_return:
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        caught_result = emission_names.temporary("caught_result")
        writer.line(
            f"let {caught_result} = __cw_catch_panic(|| {native_call})?;",
            function.span,
            "panic_boundary",
        )
        final_result = caught_result
        if function.python_boundary:
            final_result = emission_names.temporary("python_result")
            writer.line(f"let {final_result} = {caught_result}?;")
        writer.line(
            "std::result::Result::Ok("
            f"{return_class} {{ value: std::option::Option::Some({final_result}) }})"
        )
    elif function.return_type.rust_name == "Result":
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            assert python_token is not None
            native_call = f"{python_token}.detach(move || {native_call})"
        caught_result = emission_names.temporary("caught_result")
        writer.line(
            f"let {caught_result} = __cw_catch_panic(|| {native_call})?;",
            function.span,
            "panic_boundary",
        )
        final_result = caught_result
        if function.python_boundary:
            final_result = emission_names.temporary("python_result")
            writer.line(f"let {final_result} = {caught_result}?;")
        writer.line(
            f"match {final_result} {{",
            function.span,
            "abi_call",
        )
        writer.enter()
        writer.line("std::result::Result::Ok(value) => std::result::Result::Ok(value),")
        error_type = function.return_type.arguments[1].display()
        writer.line(
            "std::result::Result::Err(error) => std::result::Result::Err("
            "__CwNativeRustResultError::new_err(("
            f"{json.dumps(error_type)}, error.to_string()))),"
        )
        writer.leave()
        writer.line("}")
    elif function.python_boundary:
        writer.line(
            (f"__cw_catch_panic(|| __cw_native_{function.rust_symbol}({arguments}))?"),
            function.span,
            "abi_call",
        )
    else:
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            assert python_token is not None
            native_call = f"{python_token}.detach(move || {native_call})"
        writer.line(
            f"std::result::Result::Ok(__cw_catch_panic(|| {native_call})?)",
            function.span,
            "abi_call",
        )
    writer.leave()
    writer.line("}")


def _write_native_exceptions(writer: _Writer) -> None:
    """Declare private, identity-bearing failures for the generated ABI."""

    for _, rust_name in _NATIVE_EXCEPTION_TYPES:
        writer.line(
            f"{PYO3_CARGO_ALIAS}::create_exception!("
            f"__crabwalk_module, {rust_name}, "
            f"{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError);"
        )


def _native_move_error(parameter: str, message: str = "value was moved") -> str:
    return (
        "__CwNativeMoveError::new_err(("
        f"{json.dumps(parameter)}, {json.dumps(message)}))"
    )


def _write_panic_boundary(writer: _Writer) -> None:
    writer.line(
        "fn __cw_panic_message(payload: Box<dyn std::any::Any + Send>) -> String {"
    )
    writer.enter()
    writer.line(
        "if let std::option::Option::Some(value) = payload.downcast_ref::<&str>() {"
    )
    writer.enter()
    writer.line("(*value).to_owned()")
    writer.leave()
    writer.line(
        "} else if let std::option::Option::Some(value) = "
        "payload.downcast_ref::<String>() {"
    )
    writer.enter()
    writer.line("value.clone()")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line('String::from("Rust panic without a string payload")')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "fn __cw_catch_panic<T, F: FnOnce() -> T>(operation: F) -> PyResult<T> {"
    )
    writer.enter()
    writer.line(
        "match std::panic::catch_unwind(std::panic::AssertUnwindSafe(operation)) {"
    )
    writer.enter()
    writer.line("std::result::Result::Ok(value) => std::result::Result::Ok(value),")
    writer.line("std::result::Result::Err(payload) => {")
    writer.enter()
    writer.line("let message = __cw_panic_message(payload);")
    writer.line("std::result::Result::Err(__CwNativePanicError::new_err(message))")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_thread_pool(writer: _Writer) -> None:
    writer.line("type __CwJob = Box<dyn FnOnce() + Send + 'static>;")
    writer.line(
        "type __CwWorkerFailure = std::sync::Arc<std::sync::Mutex<Option<String>>>;"
    )
    writer.line()
    writer.line(
        "fn __cw_record_worker_failure(failure: &__CwWorkerFailure, message: String) {"
    )
    writer.enter()
    writer.line(
        "let mut slot = failure.lock().unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("if slot.is_none() { *slot = std::option::Option::Some(message); }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwThreadPool {")
    writer.enter()
    writer.line("workers: Vec<__CwWorker>,")
    writer.line("sender: Option<std::sync::mpsc::Sender<__CwJob>>,")
    writer.line("failure: __CwWorkerFailure,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwThreadPool {")
    writer.enter()
    writer.line("fn new(size: usize) -> Self {")
    writer.enter()
    writer.line('assert!(size > 0, "thread pool size must be positive");')
    writer.line("let (sender, receiver) = std::sync::mpsc::channel();")
    writer.line("let receiver = std::sync::Arc::new(std::sync::Mutex::new(receiver));")
    writer.line("let failure = std::sync::Arc::new(std::sync::Mutex::new(None));")
    writer.line("let mut workers = Vec::with_capacity(size);")
    writer.line("for id in 0..size {")
    writer.enter()
    writer.line(
        "workers.push(__CwWorker::new(id, std::sync::Arc::clone(&receiver), "
        "std::sync::Arc::clone(&failure)));"
    )
    writer.leave()
    writer.line("}")
    writer.line("Self { workers, sender: std::option::Option::Some(sender), failure }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn execute<F>(&self, operation: F)")
    writer.line("where")
    writer.enter()
    writer.line("F: FnOnce() + Send + 'static,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let job = Box::new(operation);")
    writer.line("self.sender.as_ref().unwrap().send(job).unwrap();")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn finish(mut self) -> Result<(), String> {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.line("let failure = {")
    writer.enter()
    writer.line(
        "let mut slot = self.failure.lock()"
        ".unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("slot.take()")
    writer.leave()
    writer.line("};")
    writer.line(
        "match failure { "
        "std::option::Option::Some(message) => std::result::Result::Err(message), "
        "std::option::Option::None => std::result::Result::Ok(()) }"
    )
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn shutdown(&mut self) {")
    writer.enter()
    writer.line("drop(self.sender.take());")
    writer.line("for worker in self.workers.drain(..) {")
    writer.enter()
    writer.line("if let std::result::Result::Err(payload) = worker.thread.join() {")
    writer.enter()
    writer.line(
        "__cw_record_worker_failure(&self.failure, __cw_panic_message(payload));"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl Drop for __CwThreadPool {")
    writer.enter()
    writer.line("fn drop(&mut self) {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwWorker {")
    writer.enter()
    writer.line("_id: usize,")
    writer.line("thread: std::thread::JoinHandle<()>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwWorker {")
    writer.enter()
    writer.line(
        "fn new(id: usize, receiver: "
        "std::sync::Arc<std::sync::Mutex<std::sync::mpsc::Receiver<__CwJob>>>, "
        "failure: __CwWorkerFailure) "
        "-> Self {"
    )
    writer.enter()
    writer.line("let thread = std::thread::spawn(move || loop {")
    writer.enter()
    writer.line("let message = receiver.lock()")
    writer.enter()
    writer.line(".unwrap_or_else(|poisoned| poisoned.into_inner())")
    writer.line(".recv();")
    writer.leave()
    writer.line("match message {")
    writer.enter()
    writer.line("std::result::Result::Ok(job) => {")
    writer.enter()
    writer.line(
        "if let std::result::Result::Err(payload) = std::panic::catch_unwind("
        "std::panic::AssertUnwindSafe(job)) {"
    )
    writer.enter()
    writer.line("__cw_record_worker_failure(&failure, __cw_panic_message(payload));")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("std::result::Result::Err(_) => break,")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("});")
    writer.line("Self { _id: id, thread }")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_block_on_executor(writer: _Writer) -> None:
    """Emit the minimal std-only executor used by explicit rust.block_on calls.

    It is intentionally educational rather than a replacement for Tokio or async-std:
    a pending future yields the OS thread and is polled again. The implementation is
    safe Rust, deterministic, and sufficient for the self-contained Book examples.
    """

    writer.line("struct __CwNoopWake;")
    writer.line("impl std::task::Wake for __CwNoopWake {")
    writer.enter()
    writer.line("fn wake(self: std::sync::Arc<Self>) {}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_yield_now() {")
    writer.enter()
    writer.line("let mut yielded = false;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if yielded {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("yielded = true;")
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_sleep_millis(milliseconds: u64) {")
    writer.enter()
    writer.line(
        "let deadline = std::time::Instant::now() "
        "+ std::time::Duration::from_millis(milliseconds);"
    )
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if std::time::Instant::now() >= deadline {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_join2<A: std::future::Future, B: std::future::Future>(")
    writer.enter()
    writer.line("left: A,")
    writer.line("right: B,")
    writer.leave()
    writer.line(") -> (A::Output, B::Output) {")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("let mut left_output = None;")
    writer.line("let mut right_output = None;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if left_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("left_output = std::option::Option::Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if right_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("right_output = std::option::Option::Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if left_output.is_some() && right_output.is_some() {")
    writer.enter()
    writer.line(
        "std::task::Poll::Ready((left_output.take().unwrap(), "
        "right_output.take().unwrap()))"
    )
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_select2<A, B>(left: A, right: B) -> A::Output")
    writer.line("where")
    writer.enter()
    writer.line("A: std::future::Future,")
    writer.line("B: std::future::Future<Output = A::Output>,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "async fn __cw_recv_async<T>(receiver: &std::sync::mpsc::Receiver<T>) -> T {"
    )
    writer.enter()
    writer.line("std::future::poll_fn(|context| match receiver.try_recv() {")
    writer.enter()
    writer.line("std::result::Result::Ok(value) => std::task::Poll::Ready(value),")
    writer.line("std::result::Result::Err(std::sync::mpsc::TryRecvError::Empty) => {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.line(
        "std::result::Result::Err("
        "std::sync::mpsc::TryRecvError::Disconnected) => "
        'panic!("async channel disconnected"),'
    )
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __cw_block_on<F: std::future::Future>(future: F) -> F::Output {")
    writer.enter()
    writer.line(
        "let waker = std::task::Waker::from(std::sync::Arc::new(__CwNoopWake));"
    )
    writer.line("let mut context = std::task::Context::from_waker(&waker);")
    writer.line("let mut future = std::pin::pin!(future);")
    writer.line("loop {")
    writer.enter()
    writer.line("match std::future::Future::poll(future.as_mut(), &mut context) {")
    writer.enter()
    writer.line("std::task::Poll::Ready(value) => return value,")
    writer.line("std::task::Poll::Pending => std::thread::yield_now(),")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def function_releases_gil(function: FunctionIR) -> bool:
    """Whether an exported wrapper can detach from Python for the native call."""

    effects = set(function.effects)
    if effects & {
        Effect.OPAQUE_CRATE_CALL,
        Effect.PYTHON_RUNTIME,
        Effect.GLOBAL_MUTATION,
        Effect.UNSAFE_MEMORY,
        Effect.UNSAFE_FFI,
    }:
        return False
    if any(
        parameter.type_ref.ownership is not None for parameter in function.parameters
    ):
        return False
    safe_names = {
        "i8",
        "i16",
        "i32",
        "i64",
        "i128",
        "u8",
        "u16",
        "u32",
        "u64",
        "u128",
        "usize",
        "f32",
        "f64",
        "bool",
        "char",
        "Unit",
    }
    return (
        all(
            parameter.type_ref.rust_name in safe_names
            for parameter in function.parameters
        )
        and function.return_type.rust_name in safe_names
    )


def _owned_vector_types(ir: PackageIR) -> tuple[TypeRef, ...]:
    values: dict[str, TypeRef] = {}
    for function in ir.functions:
        if not function.exported:
            continue
        for parameter in function.parameters:
            if (
                parameter.type_ref.ownership is not None
                and parameter.type_ref.underlying.rust_name == "Vec"
            ):
                vector = parameter.type_ref.underlying
                values[vector.render()] = vector
        if (
            function.return_type.ownership == "Owned"
            and function.return_type.underlying.rust_name == "Vec"
        ):
            vector = function.return_type.underlying
            values[vector.render()] = vector
    return tuple(values[key] for key in sorted(values))


def _write_owned_vector_class(
    writer: _Writer,
    vector_type: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(vector_type)
    rendered = vector_type.render()
    element_type = vector_type.arguments[0]
    domain_type = domains_by_symbol.get(element_type.rust_name)
    domain_class = (
        owned_class_names(domain_type)[1] if domain_type is not None else None
    )
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{rendered}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("#[new]")
    if domain_class is None:
        writer.line(f"fn new(value: {rendered}) -> Self {{")
        writer.enter()
        writer.line("Self { value: std::option::Option::Some(value) }")
        writer.leave()
        writer.line("}")
    else:
        writer.line(
            f"fn new(value: Vec<PyRef<'_, {domain_class}>>) -> PyResult<Self> {{"
        )
        writer.enter()
        constructor_names = EmissionNames.reserving("value")
        values = constructor_names.temporary("owned_values")
        item = constructor_names.temporary("owned_item")
        item_value = constructor_names.temporary("owned_item_value")
        writer.line(f"let mut {values} = Vec::with_capacity(value.len());")
        writer.line(f"for {item} in value {{")
        writer.enter()
        writer.line(f"let {item_value} = {item}.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"{values}.push({item_value}.clone());")
        writer.leave()
        writer.line("}")
        writer.line(
            "std::result::Result::Ok(Self { "
            f"value: std::option::Option::Some({values}) }})"
        )
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn __len__(&self) -> PyResult<usize> {")
    writer.enter()
    writer.line("self.value.as_ref().map(|value| value.len()).ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line()
    if domain_class is None:
        writer.line(f"fn to_python(&self) -> PyResult<{rendered}> {{")
        writer.enter()
        writer.line("self.value.as_ref().cloned().ok_or_else(|| {")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})")
        writer.leave()
        writer.line("}")
    else:
        to_python_names = EmissionNames.reserving("self", "py")
        values = to_python_names.temporary("stored_values")
        item = to_python_names.temporary("stored_item")
        writer.line(
            f"fn to_python(&self, py: Python<'_>) -> PyResult<Vec<Py<{domain_class}>>> {{"
        )
        writer.enter()
        writer.line(f"let {values} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"{values}.iter().cloned().map(|{item}| {{")
        writer.enter()
        writer.line(
            f"Py::new(py, {domain_class} {{ "
            f"value: std::option::Option::Some({item}) }})"
        )
        writer.leave()
        writer.line("}).collect()")
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{python_name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{python_name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _wrapper_parameter(parameter: ParameterIR) -> str:
    ownership = parameter.type_ref.ownership
    if ownership is None:
        return f"{parameter.rust_name}: {parameter.type_ref.render()}"
    vector = parameter.type_ref.underlying
    _, rust_class = owned_class_names(vector)
    if ownership == "Ref":
        return f"{parameter.rust_name}: PyRef<'_, {rust_class}>"
    return f"mut {parameter.rust_name}: PyRefMut<'_, {rust_class}>"


def _write_wrapper_extraction(
    writer: _Writer,
    parameter: ParameterIR,
    extracted_name: str | None,
) -> None:
    ownership = parameter.type_ref.ownership
    if ownership is None:
        assert extracted_name is None
        return
    assert extracted_name is not None
    access = {
        "Owned": "take()",
        "Ref": "as_ref()",
        "Mut": "as_mut()",
    }[ownership]
    writer.line(
        (
            f"let {extracted_name} = "
            f"{parameter.rust_name}.value.{access}.ok_or_else(|| "
            f"{_native_move_error(parameter.name)})?;"
        ),
        parameter.span,
        "ownership_boundary",
    )


def _write_wrapper_ownership_preflight(
    writer: _Writer,
    parameter: ParameterIR,
) -> None:
    if parameter.type_ref.ownership is None:
        return
    writer.line(
        (
            f"if {parameter.rust_name}.value.is_none() {{ "
            f"return std::result::Result::Err("
            f"{_native_move_error(parameter.name)}); }}"
        ),
        parameter.span,
        "ownership_preflight",
    )
