"""Deterministic Rust and Cargo generation from semantic IR."""

from __future__ import annotations

import json
import hashlib
from dataclasses import dataclass

from crabwalk.native_exceptions import (
    NATIVE_BORROW_ERROR,
    NATIVE_MOVE_ERROR,
    NATIVE_PANIC_ERROR,
    NATIVE_RUST_RESULT_ERROR,
)

from .ir import (
    Effect,
    EnumIR,
    FunctionIR,
    PackageIR,
    ParameterIR,
    StructIR,
    TraitIR,
    TypeRef,
)
from .cargo_emission import render_build_rs, render_cargo_toml
from .emission import EmissionNames, Writer as _Writer
from .rust_emission import write_native_function as _write_native_function
from .types import ExternalType
from .naming import (
    PYO3_CARGO_ALIAS,
    cargo_dependency_key,
    owned_class_names,
    shared_class_names,
)

CODEGEN_SCHEMA_VERSION = 45

_NATIVE_EXCEPTION_TYPES = (
    (NATIVE_MOVE_ERROR, "__CwNativeMoveError"),
    (NATIVE_BORROW_ERROR, "__CwNativeBorrowError"),
    (NATIVE_PANIC_ERROR, "__CwNativePanicError"),
    (NATIVE_RUST_RESULT_ERROR, "__CwNativeRustResultError"),
)


@dataclass(frozen=True, slots=True)
class GeneratedProject:
    cargo_toml: str
    build_rs: str
    rust_source: str
    source_map: dict[str, object]
    ir_json: str


def generate_project(
    ir: PackageIR,
    extension_name: str,
    *,
    cargo_package_identity: str | None = None,
) -> GeneratedProject:
    from .validation import validate_package_ir

    validate_package_ir(ir)
    writer = _Writer()
    domains_by_symbol = {value.symbol: value.type_ref for value in ir.structs}
    domains_by_symbol.update({value.symbol: value.type_ref for value in ir.enums})
    structs_by_symbol = {value.symbol: value for value in ir.structs}
    enums_by_symbol = {value.symbol: value for value in ir.enums if not value.is_error}
    error_enums_by_symbol = {
        value.symbol: value for value in ir.enums if value.is_error
    }
    boundary_names = {
        function.rust_symbol for function in ir.functions if function.python_boundary
    }
    writer.line("// Generated by Crabwalk. Inspectable; do not edit.")
    writer.line(
        f"// IR schema: {ir.schema_version}; codegen schema: {CODEGEN_SCHEMA_VERSION}"
    )
    writer.line(f"extern crate {PYO3_CARGO_ALIAS} as pyo3;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        cargo_key = cargo_dependency_key(dependency.package, dependency.binding)
        writer.line(f"extern crate {cargo_key} as {dependency.binding};")
    writer.line(f"use {PYO3_CARGO_ALIAS}::prelude::*;")
    if ir.structs or any(_enum_has_heterogeneous_fields(value) for value in ir.enums):
        writer.line(f"use {PYO3_CARGO_ALIAS}::IntoPyObjectExt;")
    for dependency in sorted(ir.crates, key=lambda value: value.binding):
        if dependency.package == "rayon":
            writer.line(f"use {dependency.binding}::prelude::*;")
    writer.line("mod __crabwalk_ffi {")
    writer.enter()
    writer.line('unsafe extern "C" {')
    writer.enter()
    writer.line('#[link_name = "abs"]')
    writer.line("pub(super) fn c_abs(input: i32) -> i32;")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    _write_native_exceptions(writer)
    writer.line()
    _write_panic_boundary(writer)
    writer.line()
    if any(
        parameter.type_ref.underlying.rust_name == "Buffer"
        for function in ir.functions
        for parameter in function.parameters
    ):
        _write_buffer_support(writer)
        writer.line()
    owned_text_column = _owned_text_column_type(ir)
    if owned_text_column is not None:
        _write_text_column_support(writer, owned_text_column)
        writer.line()
    _write_thread_pool(writer)
    writer.line()

    if any(function.is_async for function in ir.functions):
        _write_block_on_executor(writer)
        writer.line()

    for trait in ir.traits:
        if trait.external_path is None:
            _write_native_trait(writer, trait)
            writer.line()

    for enum in ir.enums:
        _write_native_enum(writer, enum)
        writer.line()
        if enum.is_error:
            _write_native_error_impls(writer, enum)
        else:
            _write_owned_enum_class(writer, enum, domains_by_symbol)
        writer.line()

    for struct in ir.structs:
        _write_native_struct(writer, struct)
        writer.line()
        _write_owned_struct_class(writer, struct, domains_by_symbol)
        writer.line()

    owned_vectors = _owned_vector_types(ir)
    domain_vector_elements = tuple(
        value.arguments[0]
        for value in owned_vectors
        if _contains_domain(value.arguments[0], domains_by_symbol)
    )
    if domain_vector_elements:
        _write_bulk_input_extractors(
            writer,
            domain_vector_elements,
            structs_by_symbol,
            enums_by_symbol,
        )
        writer.line()
    for vector_type in owned_vectors:
        _write_owned_vector_class(
            writer,
            vector_type,
            domains_by_symbol,
        )
        writer.line()

    owned_external_types = _owned_external_types(ir)
    for external_type in owned_external_types:
        _write_owned_external_class(writer, external_type)
        writer.line()

    shared_types = _shared_types(ir)
    for shared_type in shared_types:
        _write_shared_class(writer, shared_type)
        writer.line()

    for function in ir.functions:
        _write_native_function(writer, function, boundary_names)
        writer.line()

    _write_method_impls(writer, ir)

    for function in ir.functions:
        if function.exported:
            _write_export_wrapper(
                writer,
                function,
                boundary_names,
                error_enums_by_symbol,
            )
            writer.line()

    writer.line(f'#[pymodule(name = "{extension_name}")]')
    writer.line("fn __crabwalk_module(m: &Bound<'_, PyModule>) -> PyResult<()> {")
    writer.enter()
    for python_name, rust_name in _NATIVE_EXCEPTION_TYPES:
        writer.line(f'm.add("{python_name}", m.py().get_type::<{rust_name}>())?;')
    for function in ir.functions:
        if not function.exported:
            continue
        writer.line(
            f"m.add_function({PYO3_CARGO_ALIAS}::wrap_pyfunction!({function.rust_symbol}, m)?)?;",
            function.span,
            "abi_export",
        )
    for vector_type in owned_vectors:
        _, rust_class = owned_class_names(vector_type)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for external_type in owned_external_types:
        _, rust_class = owned_class_names(external_type)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    if owned_text_column is not None:
        _, rust_class = owned_class_names(owned_text_column)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for shared_type in shared_types:
        _, rust_class = shared_class_names(shared_type)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for struct in ir.structs:
        _, rust_class = owned_class_names(struct.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    for enum in ir.enums:
        if enum.is_error:
            continue
        _, rust_class = owned_class_names(enum.type_ref)
        writer.line(f"m.add_class::<{rust_class}>()?;")
    writer.line("std::result::Result::Ok(())")
    writer.leave()
    writer.line("}")

    source_map = {
        "schema_version": 2,
        "generated_file": "src/lib.rs",
        "source_hash": ir.source_hash,
        "compiler_input_hash": ir.compiler_input_hash,
        "wheel_source_integrity_hash": ir.wheel_source_integrity_hash,
        "entries": writer.mappings,
    }
    return GeneratedProject(
        cargo_toml=render_cargo_toml(
            ir,
            extension_name,
            cargo_package_identity,
        ),
        build_rs=render_build_rs(extension_name),
        rust_source=writer.render(),
        source_map=source_map,
        ir_json=json.dumps(ir.to_dict(), indent=2, sort_keys=True) + "\n",
    )


def _write_native_struct(writer: _Writer, struct: StructIR) -> None:
    derives = ["Clone", "Debug"] + ["::".join(value) for value in struct.derives]
    writer.line(f"#[derive({', '.join(derives)})]", struct.span, "struct_derive")
    writer.line(f"struct {struct.symbol} {{", struct.span, "struct")
    writer.enter()
    for field in struct.fields:
        writer.line(
            f"pub {field.rust_name}: {field.type_ref.render()},",
            field.span,
            "struct_field",
        )
    writer.leave()
    writer.line("}")


def _write_native_trait(writer: _Writer, trait: TraitIR) -> None:
    writer.line(f"trait {trait.symbol} {{", trait.span, "trait")
    writer.enter()
    associated_names: set[str] = set()

    def collect_associated(type_ref: TypeRef) -> None:
        if type_ref.rust_name == "Associated" and type_ref.python_name is not None:
            associated_names.add(type_ref.python_name)
        for argument in type_ref.arguments:
            collect_associated(argument)

    for method in trait.methods:
        collect_associated(method.return_type)
        for parameter_type in method.parameter_types:
            collect_associated(parameter_type)
    for name in sorted(associated_names):
        writer.line(f"type {name};", trait.span, "trait_associated_type")
    if associated_names:
        writer.line()
    for method in trait.methods:
        rendered_generics: list[str] = []
        for parameter in method.type_parameters:
            if parameter.is_lifetime:
                rendered_generics.append(f"'{parameter.rust_name}")
            else:
                bounds = f": {' + '.join(parameter.bounds)}" if parameter.bounds else ""
                rendered_generics.append(f"{parameter.rust_name}{bounds}")
        generics = f"<{', '.join(rendered_generics)}>" if rendered_generics else ""
        receiver = {
            "Ref": "&self",
            "Mut": "&mut self",
            "Owned": "self",
        }[method.receiver_ownership]
        parameters = tuple(
            f"__cw_trait_arg_{index}: {type_ref.render()}"
            for index, type_ref in enumerate(method.parameter_types)
        )
        signature = ", ".join((receiver, *parameters))
        writer.line(
            f"fn {method.rust_name}{generics}({signature}) "
            f"-> {method.return_type.render()};",
            method.span,
            "trait_method",
        )
    writer.leave()
    writer.line("}")


def _write_method_impls(writer: _Writer, package: PackageIR) -> None:
    traits_by_symbol = {trait.symbol: trait for trait in package.traits}
    trait_method_names = {
        (trait.symbol, method.name): method.rust_name
        for trait in package.traits
        for method in trait.methods
    }
    inherent = [
        function
        for function in package.functions
        if function.method_for is not None
        and function.trait_symbol is None
        and function.operator_kind is None
    ]
    for function in inherent:
        assert function.method_for is not None and function.method_name is not None
        writer.line(f"impl {function.method_for.render()} {{")
        writer.enter()
        _write_method_glue(writer, function)
        writer.leave()
        writer.line("}")
        writer.line()

    operators = [
        function
        for function in package.functions
        if function.method_for is not None and function.operator_kind is not None
    ]
    for function in operators:
        assert function.method_for is not None
        assert function.operator_kind is not None
        assert len(function.parameters) == 2
        trait_name, method_name = {
            "add": ("Add", "add"),
            "subtract": ("Sub", "sub"),
            "multiply": ("Mul", "mul"),
            "divide": ("Div", "div"),
            "remainder": ("Rem", "rem"),
        }[function.operator_kind]
        right = function.parameters[1]
        writer.line(
            f"impl std::ops::{trait_name}<{right.type_ref.render()}> "
            f"for {function.method_for.render()} {{"
        )
        writer.enter()
        writer.line(f"type Output = {function.return_type.render()};")
        writer.line()
        writer.line(
            f"fn {method_name}(self, {right.rust_name}: {right.type_ref.render()}) "
            "-> Self::Output {",
            function.span,
            "operator_impl",
        )
        writer.enter()
        writer.line(f"__cw_native_{function.rust_symbol}(self, {right.rust_name})")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
        writer.line()

    trait_groups: dict[tuple[str, str], list[FunctionIR]] = {}
    for function in package.functions:
        if function.method_for is None or function.trait_symbol is None:
            continue
        trait_groups.setdefault(
            (function.trait_symbol, function.method_for.rust_name), []
        ).append(function)
    for (trait_symbol, _), functions in trait_groups.items():
        target = functions[0].method_for
        assert target is not None
        writer.line(f"impl {trait_symbol} for {target.render()} {{")
        writer.enter()
        associated: dict[str, TypeRef] = {}

        def bind_associated(pattern: TypeRef, concrete: TypeRef) -> None:
            if pattern.rust_name == "Associated":
                assert pattern.python_name is not None
                previous = associated.get(pattern.python_name)
                if previous is not None and previous != concrete:
                    raise AssertionError("validated associated type mapping diverged")
                associated[pattern.python_name] = concrete
                return
            if len(pattern.arguments) != len(concrete.arguments):
                return
            for pattern_arg, concrete_arg in zip(
                pattern.arguments, concrete.arguments, strict=True
            ):
                bind_associated(pattern_arg, concrete_arg)

        trait = traits_by_symbol[trait_symbol]
        for function in functions:
            declared = next(
                method
                for method in trait.methods
                if method.name == function.method_name
            )
            bind_associated(declared.return_type, function.return_type)
            for pattern, parameter in zip(
                declared.parameter_types,
                function.parameters[1:],
                strict=True,
            ):
                bind_associated(pattern, parameter.type_ref)
        for name, type_ref in sorted(associated.items()):
            writer.line(f"type {name} = {type_ref.render()};")
        if associated:
            writer.line()
        for function in functions:
            assert function.method_name is not None
            _write_method_glue(
                writer,
                function,
                trait_method_names[(trait_symbol, function.method_name)],
            )
        writer.leave()
        writer.line("}")
        writer.line()


def _write_method_glue(
    writer: _Writer,
    function: FunctionIR,
    emitted_method_name: str | None = None,
) -> None:
    assert function.method_name is not None and function.parameters
    receiver_type = function.parameters[0].type_ref
    rendered_generics: list[str] = []
    for parameter in function.type_parameters:
        if parameter.is_lifetime:
            rendered_generics.append(f"'{parameter.rust_name}")
        else:
            qualified = tuple(
                {
                    "Clone": "std::clone::Clone",
                    "Copy": "std::marker::Copy",
                    "Debug": "std::fmt::Debug",
                    "Display": "std::fmt::Display",
                    "Ord": "std::cmp::Ord",
                    "PartialOrd": "std::cmp::PartialOrd",
                }.get(value, value)
                for value in parameter.bounds
            )
            bounds = f": {' + '.join(qualified)}" if qualified else ""
            rendered_generics.append(f"{parameter.rust_name}{bounds}")
    generics = f"<{', '.join(rendered_generics)}>" if rendered_generics else ""
    receiver = {
        "Ref": "&self",
        "Mut": "&mut self",
        "Owned": "self",
    }[receiver_type.rust_name]
    tail = [
        f"{parameter.rust_name}: {parameter.type_ref.render()}"
        for parameter in function.parameters[1:]
    ]
    parameters = ", ".join((receiver, *tail))
    arguments = ", ".join(
        ("self", *(parameter.rust_name for parameter in function.parameters[1:]))
    )
    return_type = (
        f"PyResult<{function.return_type.render()}>"
        if function.python_boundary
        else function.return_type.render()
    )
    writer.line(
        f"fn {emitted_method_name or function.method_name}{generics}({parameters}) "
        f"-> {return_type} {{",
        function.span,
        "method_impl",
    )
    writer.enter()
    writer.line(f"__cw_native_{function.rust_symbol}({arguments})")
    writer.leave()
    writer.line("}")


def _write_native_enum(writer: _Writer, enum: EnumIR) -> None:
    derives = (["Debug"] if enum.is_error else ["Clone", "Debug"]) + [
        "::".join(value) for value in enum.derives
    ]
    writer.line(f"#[derive({', '.join(derives)})]", enum.span, "enum_derive")
    writer.line(f"enum {enum.symbol} {{", enum.span, "enum")
    writer.enter()
    for variant in enum.variants:
        if not variant.fields:
            writer.line(f"{variant.rust_name},", variant.span, "enum_variant")
        elif variant.tuple_style:
            fields = ", ".join(field.type_ref.render() for field in variant.fields)
            writer.line(f"{variant.rust_name}({fields}),", variant.span, "enum_variant")
        else:
            writer.line(f"{variant.rust_name} {{", variant.span, "enum_variant")
            writer.enter()
            for field in variant.fields:
                writer.line(
                    f"{field.rust_name}: {field.type_ref.render()},",
                    field.span,
                    "enum_field",
                )
            writer.leave()
            writer.line("},")
    writer.leave()
    writer.line("}")


def _write_native_error_impls(writer: _Writer, enum: EnumIR) -> None:
    """Emit declared conversions and structured, source-preserving error metadata."""

    writer.line(f"impl std::fmt::Display for {enum.symbol} {{")
    writer.enter()
    writer.line(
        "fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {"
    )
    writer.enter()
    writer.line('write!(formatter, "{:?}", self)')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()

    writer.line(f"impl std::error::Error for {enum.symbol} {{")
    writer.enter()
    writer.line(
        "fn source(&self) -> std::option::Option<&(dyn std::error::Error + 'static)> {"
    )
    writer.enter()
    writer.line("match self {")
    writer.enter()
    for variant in enum.variants:
        source = variant.from_source
        if source is None or not (
            source.rust_name == "IoError" or _is_error_domain_type(source)
        ):
            continue
        source_binding = "__cw_source"
        pattern = _enum_variant_pattern(
            enum,
            variant.name,
            ((variant.fields[0].name, source_binding),),
            variant.tuple_style,
        )
        writer.line(f"{pattern} => std::option::Option::Some({source_binding}),")
    writer.line("_ => std::option::Option::None,")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()

    for variant in enum.variants:
        source = variant.from_source
        if source is None:
            continue
        writer.line(f"impl std::convert::From<{source.render()}> for {enum.symbol} {{")
        writer.enter()
        writer.line(f"fn from(source: {source.render()}) -> Self {{")
        writer.enter()
        writer.line(f"Self::{variant.rust_name}(source)")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
        writer.line()

    writer.line(f"impl {enum.symbol} {{")
    writer.enter()
    writer.line("fn __cw_variant(&self) -> &'static str {")
    writer.enter()
    writer.line("match self {")
    writer.enter()
    for variant in enum.variants:
        pattern = _enum_variant_pattern(enum, variant.name, (), variant.tuple_style)
        writer.line(f'{pattern} => "{variant.name}",')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()

    writer.line("fn __cw_fields(&self) -> Vec<(String, String)> {")
    writer.enter()
    writer.line("match self {")
    writer.enter()
    for variant_index, variant in enumerate(enum.variants):
        bindings = tuple(
            (field.name, f"__cw_field_{variant_index}_{field_index}")
            for field_index, field in enumerate(variant.fields)
        )
        pattern = _enum_variant_pattern(
            enum,
            variant.name,
            bindings,
            variant.tuple_style,
        )
        if not variant.fields:
            writer.line(f"{pattern} => Vec::new(),")
            continue
        values = ", ".join(
            (
                f'(String::from("{_error_field_name(variant, field.name)}"), '
                f'format!("{{}}", {binding}))'
            )
            for field, (_, binding) in zip(variant.fields, bindings)
        )
        writer.line(f"{pattern} => vec![{values}],")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()

    writer.line("fn __cw_sources(&self) -> Vec<(String, String)> {")
    writer.enter()
    writer.line("match self {")
    writer.enter()
    for variant in enum.variants:
        source = variant.from_source
        if source is None:
            continue
        source_binding = "__cw_source"
        pattern = _enum_variant_pattern(
            enum,
            variant.name,
            ((variant.fields[0].name, source_binding),),
            variant.tuple_style,
        )
        source_type = json.dumps(source.display())
        if _is_error_domain_type(source):
            writer.line(f"{pattern} => {{")
            writer.enter()
            writer.line(
                f"let mut __cw_sources = vec![(String::from({source_type}), "
                f"{source_binding}.to_string())];"
            )
            writer.line(f"__cw_sources.extend({source_binding}.__cw_sources());")
            writer.line("__cw_sources")
            writer.leave()
            writer.line("},")
        else:
            writer.line(
                f"{pattern} => vec![(String::from({source_type}), "
                f"{source_binding}.to_string())],"
            )
    writer.line("_ => Vec::new(),")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _is_error_domain_type(type_ref: TypeRef) -> bool:
    from .types import ErrorDomainType

    return isinstance(type_ref, ErrorDomainType)


def _error_field_name(variant: object, field_name: str) -> str:
    from_source = getattr(variant, "from_source", None)
    return "source" if from_source is not None and field_name == "_0" else field_name


def _domain_class(
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> str | None:
    domain = domains_by_symbol.get(type_ref.rust_name)
    return owned_class_names(domain)[1] if domain is not None else None


def _contains_domain(
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> bool:
    return _domain_class(type_ref, domains_by_symbol) is not None or any(
        _contains_domain(value, domains_by_symbol) for value in type_ref.arguments
    )


def _domain_input_type(
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> str:
    domain_class = _domain_class(type_ref, domains_by_symbol)
    if domain_class is not None:
        return f"PyRef<'_, {domain_class}>"
    if type_ref.rust_name == "Vec" and len(type_ref.arguments) == 1:
        return f"Vec<{_domain_input_type(type_ref.arguments[0], domains_by_symbol)}>"
    if type_ref.rust_name == "Option" and len(type_ref.arguments) == 1:
        return f"Option<{_domain_input_type(type_ref.arguments[0], domains_by_symbol)}>"
    if type_ref.rust_name == "Tuple" and type_ref.arguments:
        values = ", ".join(
            _domain_input_type(value, domains_by_symbol) for value in type_ref.arguments
        )
        return f"({values}{',' if len(type_ref.arguments) == 1 else ''})"
    if type_ref.rust_name == "HashMap" and len(type_ref.arguments) == 2:
        key, value = type_ref.arguments
        return (
            "std::collections::HashMap<"
            f"{_domain_input_type(key, domains_by_symbol)}, "
            f"{_domain_input_type(value, domains_by_symbol)}>"
        )
    return type_ref.render()


def _domain_input_conversion(
    expression: str,
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
    names: EmissionNames,
    field_name: str,
) -> str:
    if _domain_class(type_ref, domains_by_symbol) is not None:
        return (
            f"{expression}.value.as_ref().cloned().ok_or_else(|| "
            f"{_native_move_error(field_name)})"
        )
    if type_ref.rust_name == "Vec" and len(type_ref.arguments) == 1:
        item = names.temporary("domain_input_item")
        child = _domain_input_conversion(
            item,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
            field_name,
        )
        return (
            f"{expression}.into_iter().map(|{item}| {child})"
            ".collect::<PyResult<Vec<_>>>()"
        )
    if type_ref.rust_name == "Option" and len(type_ref.arguments) == 1:
        item = names.temporary("domain_input_item")
        child = _domain_input_conversion(
            item,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
            field_name,
        )
        return (
            f"match {expression} {{ std::option::Option::Some({item}) => "
            f"({child}).map(std::option::Option::Some), "
            "std::option::Option::None => "
            "std::result::Result::<_, pyo3::PyErr>::Ok("
            "std::option::Option::None) }"
        )
    if type_ref.rust_name == "Tuple" and type_ref.arguments:
        values = ", ".join(
            f"({_domain_input_conversion(f'({expression}).{index}', child, domains_by_symbol, names, field_name)})?"
            for index, child in enumerate(type_ref.arguments)
        )
        suffix = "," if len(type_ref.arguments) == 1 else ""
        return f"std::result::Result::<_, pyo3::PyErr>::Ok(({values}{suffix}))"
    if type_ref.rust_name == "HashMap" and len(type_ref.arguments) == 2:
        key_name = names.temporary("domain_input_key")
        value_name = names.temporary("domain_input_value")
        key = _domain_input_conversion(
            key_name,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
            field_name,
        )
        value = _domain_input_conversion(
            value_name,
            type_ref.arguments[1],
            domains_by_symbol,
            names,
            field_name,
        )
        return (
            f"{expression}.into_iter().map(|({key_name}, {value_name})| "
            f"std::result::Result::<_, pyo3::PyErr>::Ok((({key})?, ({value})?)))"
            ".collect::<PyResult<std::collections::HashMap<_, _>>>()"
        )
    return f"std::result::Result::<_, pyo3::PyErr>::Ok({expression})"


def _domain_output_type(
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> str:
    domain_class = _domain_class(type_ref, domains_by_symbol)
    if domain_class is not None:
        return f"Py<{domain_class}>"
    if type_ref.rust_name == "Vec" and len(type_ref.arguments) == 1:
        return f"Vec<{_domain_output_type(type_ref.arguments[0], domains_by_symbol)}>"
    if type_ref.rust_name == "Option" and len(type_ref.arguments) == 1:
        return (
            f"Option<{_domain_output_type(type_ref.arguments[0], domains_by_symbol)}>"
        )
    if type_ref.rust_name == "Tuple" and type_ref.arguments:
        values = ", ".join(
            _domain_output_type(value, domains_by_symbol)
            for value in type_ref.arguments
        )
        return f"({values}{',' if len(type_ref.arguments) == 1 else ''})"
    if type_ref.rust_name == "HashMap" and len(type_ref.arguments) == 2:
        key, value = type_ref.arguments
        return (
            "std::collections::HashMap<"
            f"{_domain_output_type(key, domains_by_symbol)}, "
            f"{_domain_output_type(value, domains_by_symbol)}>"
        )
    return type_ref.render()


def _domain_output_conversion(
    expression: str,
    type_ref: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
    names: EmissionNames,
) -> str:
    domain_class = _domain_class(type_ref, domains_by_symbol)
    if domain_class is not None:
        return (
            f"Py::new(py, {domain_class} {{ value: "
            f"std::option::Option::Some((*({expression})).clone()) }})"
        )
    if type_ref.rust_name == "Vec" and len(type_ref.arguments) == 1:
        item = names.temporary("domain_output_item")
        child = _domain_output_conversion(
            item,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
        )
        return (
            f"({expression}).iter().map(|{item}| {child}).collect::<PyResult<Vec<_>>>()"
        )
    if type_ref.rust_name == "Option" and len(type_ref.arguments) == 1:
        item = names.temporary("domain_output_item")
        child = _domain_output_conversion(
            item,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
        )
        return f"({expression}).as_ref().map(|{item}| {child}).transpose()"
    if type_ref.rust_name == "Tuple" and type_ref.arguments:
        values = ", ".join(
            f"({_domain_output_conversion(f'&({expression}).{index}', child, domains_by_symbol, names)})?"
            for index, child in enumerate(type_ref.arguments)
        )
        suffix = "," if len(type_ref.arguments) == 1 else ""
        return f"std::result::Result::<_, pyo3::PyErr>::Ok(({values}{suffix}))"
    if type_ref.rust_name == "HashMap" and len(type_ref.arguments) == 2:
        key_name = names.temporary("domain_output_key")
        value_name = names.temporary("domain_output_value")
        key = _domain_output_conversion(
            key_name,
            type_ref.arguments[0],
            domains_by_symbol,
            names,
        )
        value = _domain_output_conversion(
            value_name,
            type_ref.arguments[1],
            domains_by_symbol,
            names,
        )
        return (
            f"({expression}).iter().map(|({key_name}, {value_name})| "
            f"std::result::Result::<_, pyo3::PyErr>::Ok((({key})?, ({value})?)))"
            ".collect::<PyResult<std::collections::HashMap<_, _>>>()"
        )
    return f"std::result::Result::<_, pyo3::PyErr>::Ok((*({expression})).clone())"


def _write_owned_enum_class(
    writer: _Writer,
    enum: EnumIR,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(enum.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{enum.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line("#[allow(non_snake_case)]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()

    for variant in enum.variants:
        constructor_names = EmissionNames.reserving(
            *(field.rust_name for field in variant.fields)
        )
        extracted_fields: dict[str, str] = {}
        parameters = ", ".join(
            f"{field.rust_name}: "
            f"{_domain_input_type(field.type_ref, domains_by_symbol)}"
            for field in variant.fields
        )
        fallible = any(
            _contains_domain(field.type_ref, domains_by_symbol)
            for field in variant.fields
        )
        writer.line("#[staticmethod]")
        return_type = "PyResult<Self>" if fallible else "Self"
        if variant.rust_name != variant.name:
            writer.line(f'#[pyo3(name = "{variant.name}")]')
        writer.line(f"fn {variant.rust_name}({parameters}) -> {return_type} {{")
        writer.enter()
        for field in variant.fields:
            if not _contains_domain(field.type_ref, domains_by_symbol):
                continue
            extracted_field = constructor_names.temporary(f"field_{field.name}")
            extracted_fields[field.name] = extracted_field
            writer.line(
                f"let {extracted_field}: {field.type_ref.render()} = "
                f"{_domain_input_conversion(field.rust_name, field.type_ref, domains_by_symbol, constructor_names, field.name)}?;"
            )
        if not variant.fields:
            value = f"{enum.symbol}::{variant.rust_name}"
        elif variant.tuple_style:
            arguments = ", ".join(
                (
                    extracted_fields[field.name]
                    if _contains_domain(field.type_ref, domains_by_symbol)
                    else field.rust_name
                )
                for field in variant.fields
            )
            value = f"{enum.symbol}::{variant.rust_name}({arguments})"
        else:
            arguments = ", ".join(
                (
                    f"{field.rust_name}: {extracted_fields[field.name]}"
                    if _contains_domain(field.type_ref, domains_by_symbol)
                    else f"{field.rust_name}: {field.rust_name}"
                )
                for field in variant.fields
            )
            value = f"{enum.symbol}::{variant.rust_name} {{ {arguments} }}"
        wrapped = f"Self {{ value: std::option::Option::Some({value}) }}"
        writer.line(f"std::result::Result::Ok({wrapped})" if fallible else wrapped)
        writer.leave()
        writer.line("}")
        writer.line()
    writer.line("fn variant(&self) -> PyResult<&'static str> {")
    writer.enter()
    writer.line("match self.value.as_ref() {")
    writer.enter()
    for variant in enum.variants:
        pattern = _enum_variant_pattern(enum, variant.name, (), variant.tuple_style)
        writer.line(
            f"std::option::Option::Some({pattern}) => "
            f'std::result::Result::Ok("{variant.name}"),'
        )
    writer.line(
        f"std::option::Option::None => std::result::Result::Err("
        f"{_native_move_error('')}),"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    for field_name, candidate_types in sorted(field_types.items()):
        heterogeneous = len(candidate_types) > 1
        field_type = next(iter(candidate_types))
        nested_domain = (
            _contains_domain(field_type, domains_by_symbol)
            if not heterogeneous
            else False
        )
        getter_names = EmissionNames.reserving("self", "py")
        stored_value = getter_names.temporary("stored_value")
        target_name = getter_names.temporary("variant_target")
        getter_field = next(
            field
            for variant in enum.variants
            for field in variant.fields
            if field.name == field_name
        )
        writer.line()
        writer.line(f'#[getter("{field_name}")]')
        if heterogeneous:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self, py: Python<'_>) -> "
                "PyResult<Option<Py<PyAny>>> {"
            )
        elif nested_domain:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self, py: Python<'_>) -> "
                f"PyResult<Option<{_domain_output_type(field_type, domains_by_symbol)}>> {{"
            )
        else:
            writer.line(
                f"fn get_{getter_field.rust_name}(&self) "
                f"-> PyResult<Option<{field_type.render()}>> {{"
            )
        writer.enter()
        writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"match {stored_value} {{")
        writer.enter()
        for variant in enum.variants:
            target = next(
                (field for field in variant.fields if field.name == field_name), None
            )
            if target is None:
                continue
            bindings = tuple(
                (field.name, target_name if field.name == field_name else "")
                for field in variant.fields
            )
            pattern = _enum_variant_pattern(
                enum,
                variant.name,
                bindings,
                variant.tuple_style,
            )
            target_has_domain = _contains_domain(target.type_ref, domains_by_symbol)
            if target_has_domain:
                native = _domain_output_conversion(
                    target_name,
                    target.type_ref,
                    domains_by_symbol,
                    getter_names,
                )
                converted = (
                    f"({native})?.into_py_any(py)?" if heterogeneous else f"({native})?"
                )
            else:
                converted = (
                    f"{target_name}.clone().into_py_any(py)?"
                    if heterogeneous
                    else f"{target_name}.clone()"
                )
            writer.line(
                f"{pattern} => std::result::Result::Ok("
                f"std::option::Option::Some({converted})),"
            )
        writer.line("_ => std::result::Result::Ok(std::option::Option::None),")
        writer.leave()
        writer.line("}")
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{enum.name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{enum.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _enum_has_heterogeneous_fields(enum: EnumIR) -> bool:
    """Return whether one Python-visible payload name has multiple Rust types.

    Rust tuple variants conventionally reuse positional names such as ``_0`` even
    though each variant is free to choose an unrelated payload type. PyO3 needs a
    single return type for a Python property, so those getters erase only the ABI
    representation to ``PyAny`` while the native enum remains fully typed.
    """

    field_types: dict[str, set[TypeRef]] = {}
    for variant in enum.variants:
        for field in variant.fields:
            field_types.setdefault(field.name, set()).add(field.type_ref)
    return any(len(value) > 1 for value in field_types.values())


def _enum_variant_pattern(
    enum: EnumIR,
    variant_name: str,
    bindings: tuple[tuple[str, str], ...],
    tuple_style: bool,
) -> str:
    variant = next(value for value in enum.variants if value.name == variant_name)
    if not variant.fields:
        return f"{enum.symbol}::{variant.rust_name}"
    values = {field: local for field, local in bindings}
    if tuple_style:
        patterns = ", ".join(values.get(field.name) or "_" for field in variant.fields)
        return f"{enum.symbol}::{variant.rust_name}({patterns})"
    patterns = ", ".join(
        f"{field.rust_name}: {values.get(field.name) or '_'}"
        for field in variant.fields
    )
    return f"{enum.symbol}::{variant.rust_name} {{ {patterns} }}"


def _write_owned_struct_class(
    writer: _Writer,
    struct: StructIR,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(struct.type_ref)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{struct.symbol}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()

    parameters = ", ".join(
        f"{field.rust_name}: {_domain_input_type(field.type_ref, domains_by_symbol)}"
        for field in struct.fields
    )
    writer.line("#[new]")
    writer.line(f"fn new({parameters}) -> PyResult<Self> {{")
    writer.enter()
    constructor_names = EmissionNames.reserving(
        *(field.rust_name for field in struct.fields)
    )
    extracted_fields: dict[str, str] = {}
    for field in struct.fields:
        if not _contains_domain(field.type_ref, domains_by_symbol):
            continue
        extracted_field = constructor_names.temporary(f"field_{field.name}")
        extracted_fields[field.name] = extracted_field
        writer.line(
            f"let {extracted_field}: {field.type_ref.render()} = "
            f"{_domain_input_conversion(field.rust_name, field.type_ref, domains_by_symbol, constructor_names, field.name)}?;"
        )
    writer.line(
        "std::result::Result::Ok(Self { value: std::option::Option::Some("
        + struct.symbol
        + " {"
    )
    writer.enter()
    for field in struct.fields:
        value = (
            extracted_fields[field.name]
            if _contains_domain(field.type_ref, domains_by_symbol)
            else field.rust_name
        )
        writer.line(f"{field.rust_name}: {value},")
    writer.leave()
    writer.line("}) })")
    writer.leave()
    writer.line("}")
    for field in struct.fields:
        nested_domain = _contains_domain(field.type_ref, domains_by_symbol)
        getter_names = EmissionNames.reserving("self", "py")
        stored_value = getter_names.temporary("stored_value")
        writer.line()
        writer.line(f'#[getter("{field.name}")]')
        if not nested_domain:
            writer.line(
                f"fn get_{field.rust_name}(&self) "
                f"-> PyResult<{field.type_ref.render()}> {{"
            )
        else:
            writer.line(
                f"fn get_{field.rust_name}(&self, py: Python<'_>) -> "
                f"PyResult<{_domain_output_type(field.type_ref, domains_by_symbol)}> {{"
            )
        writer.enter()
        writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        if not nested_domain:
            writer.line(
                f"std::result::Result::Ok({stored_value}.{field.rust_name}.clone())"
            )
        else:
            writer.line(
                _domain_output_conversion(
                    f"&{stored_value}.{field.rust_name}",
                    field.type_ref,
                    domains_by_symbol,
                    getter_names,
                )
            )
        writer.leave()
        writer.line("}")
        writer.line()
        writer.line(f'#[setter("{field.name}")]')
        setter_type = _domain_input_type(field.type_ref, domains_by_symbol)
        writer.line(
            f"fn set_{field.rust_name}(&mut self, value: {setter_type}) "
            "-> PyResult<()> {"
        )
        writer.enter()
        setter_names = EmissionNames.reserving("self", "value")
        assigned_value = "value"
        if nested_domain:
            assigned_value = setter_names.temporary("assigned_value")
            writer.line(
                f"let {assigned_value}: {field.type_ref.render()} = "
                f"{_domain_input_conversion('value', field.type_ref, domains_by_symbol, setter_names, field.name)}?;"
            )
        target = setter_names.temporary("target")
        writer.line(f"let {target} = self.value.as_mut().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(f"{target}.{field.rust_name} = {assigned_value};")
        writer.line("std::result::Result::Ok(())")
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line(
        "fn to_python(&self, py: Python<'_>) -> PyResult<Py<pyo3::types::PyTuple>> {",
        struct.span,
        "struct_to_python",
    )
    writer.enter()
    to_python_names = EmissionNames.reserving("self", "py")
    stored_value = to_python_names.temporary("stored_value")
    items = to_python_names.temporary("python_items")
    writer.line(f"let {stored_value} = self.value.as_ref().ok_or_else(|| {{")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})?;")
    converted_fields: dict[str, str] = {}
    for field in struct.fields:
        if not _contains_domain(field.type_ref, domains_by_symbol):
            continue
        converted = to_python_names.temporary(f"python_field_{field.name}")
        converted_fields[field.name] = converted
        writer.line(
            f"let {converted} = "
            f"{_domain_output_conversion(f'&{stored_value}.{field.rust_name}', field.type_ref, domains_by_symbol, to_python_names)}?;"
        )
    writer.line(f"let {items}: Vec<Py<PyAny>> = vec![")
    writer.enter()
    for field in struct.fields:
        if field.name in converted_fields:
            converted = f"{converted_fields[field.name]}.into_py_any(py)?,"
        else:
            converted = f"{stored_value}.{field.rust_name}.clone().into_py_any(py)?,"
        writer.line(converted, field.span, "struct_field_to_python")
    writer.leave()
    writer.line("];")
    writer.line(
        f"std::result::Result::Ok(pyo3::types::PyTuple::new(py, {items})?.unbind())"
    )
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{struct.name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{struct.name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_export_wrapper(
    writer: _Writer,
    function: FunctionIR,
    boundary_names: set[str],
    error_enums_by_symbol: dict[str, EnumIR],
) -> None:
    emission_names = EmissionNames.for_function(function)
    wrapper_parameters = [
        _wrapper_parameter(parameter) for parameter in function.parameters
    ]
    releases_gil = function_releases_gil(function)
    has_buffer = any(
        parameter.type_ref.underlying.rust_name == "Buffer"
        for parameter in function.parameters
    )
    needs_python_token = releases_gil or has_buffer
    python_token = (
        emission_names.temporary("python_token") if needs_python_token else None
    )
    if needs_python_token:
        assert python_token is not None
        wrapper_parameters.insert(0, f"{python_token}: Python<'_>")
    parameters = ", ".join(wrapper_parameters)
    extracted_arguments = {
        parameter.rust_name: emission_names.temporary(f"argument_{parameter.name}")
        for parameter in function.parameters
        if parameter.type_ref.ownership is not None
        or parameter.type_ref.underlying.rust_name == "Buffer"
    }
    untyped_buffers = {
        parameter.rust_name: emission_names.temporary(
            f"untyped_buffer_{parameter.name}"
        )
        for parameter in function.parameters
        if parameter.type_ref.ownership is None
        and parameter.type_ref.rust_name == "Buffer"
    }
    arguments = ", ".join(
        (
            extracted_arguments[parameter.rust_name]
            if parameter.rust_name in extracted_arguments
            else parameter.rust_name
        )
        for parameter in function.parameters
    )
    writer.line("#[pyfunction]")
    owned_return = function.return_type.ownership == "Owned"
    if owned_return:
        _, return_class = owned_class_names(function.return_type.underlying)
        wrapper_return = f"PyResult<{return_class}>"
    else:
        wrapper_return = (
            f"PyResult<{function.return_type.arguments[0].render()}>"
            if function.return_type.rust_name == "Result"
            else f"PyResult<{function.return_type.render()}>"
        )
    writer.line(
        f"fn {function.rust_symbol}({parameters}) -> {wrapper_return} {{",
        function.span,
        "abi_wrapper",
    )
    writer.enter()
    for parameter in function.parameters:
        _write_wrapper_ownership_preflight(writer, parameter)
    for parameter in function.parameters:
        _write_wrapper_buffer_preflight(
            writer,
            parameter,
            untyped_buffers.get(parameter.rust_name),
        )
    for parameter in function.parameters:
        _write_wrapper_extraction(
            writer,
            parameter,
            extracted_arguments.get(parameter.rust_name),
            python_token,
            untyped_buffers.get(parameter.rust_name),
        )
    if releases_gil:
        for parameter in function.parameters:
            if parameter.type_ref.ownership in {"Owned", "Shared"}:
                writer.line(
                    f"drop({parameter.rust_name});",
                    parameter.span,
                    "gil_release_guard_drop",
                )
    if owned_return:
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            assert python_token is not None
            native_call = f"{python_token}.detach(move || {native_call})"
        caught_result = emission_names.temporary("caught_result")
        writer.line(
            f"let {caught_result} = __cw_catch_panic(|| {native_call})?;",
            function.span,
            "panic_boundary",
        )
        final_result = caught_result
        if function.python_boundary:
            final_result = emission_names.temporary("python_result")
            writer.line(f"let {final_result} = {caught_result}?;")
        writer.line(
            "std::result::Result::Ok("
            f"{return_class} {{ value: std::option::Option::Some({final_result}) }})"
        )
    elif function.return_type.rust_name == "Result":
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            assert python_token is not None
            native_call = f"{python_token}.detach(move || {native_call})"
        caught_result = emission_names.temporary("caught_result")
        writer.line(
            f"let {caught_result} = __cw_catch_panic(|| {native_call})?;",
            function.span,
            "panic_boundary",
        )
        final_result = caught_result
        if function.python_boundary:
            final_result = emission_names.temporary("python_result")
            writer.line(f"let {final_result} = {caught_result}?;")
        writer.line(
            f"match {final_result} {{",
            function.span,
            "abi_call",
        )
        writer.enter()
        writer.line("std::result::Result::Ok(value) => std::result::Result::Ok(value),")
        error_ref = function.return_type.arguments[1]
        error_type = error_ref.display()
        error_enum = error_enums_by_symbol.get(error_ref.rust_name)
        if error_enum is None:
            writer.line(
                "std::result::Result::Err(error) => std::result::Result::Err("
                "__CwNativeRustResultError::new_err(("
                f"{json.dumps(error_type)}, error.to_string()))),"
            )
        else:
            writer.line(
                "std::result::Result::Err(error) => {",
                error_enum.span,
                "structured_error_boundary",
            )
            writer.enter()
            writer.line("let __cw_message = error.to_string();")
            writer.line("let __cw_variant = error.__cw_variant();")
            writer.line("let __cw_fields = error.__cw_fields();")
            writer.line("let __cw_sources = error.__cw_sources();")
            writer.line(
                "std::result::Result::Err(__CwNativeRustResultError::new_err(("
                f"{json.dumps(error_type)}, __cw_message, __cw_variant, "
                "__cw_fields, __cw_sources)))"
            )
            writer.leave()
            writer.line("},")
        writer.leave()
        writer.line("}")
    elif function.python_boundary:
        writer.line(
            (f"__cw_catch_panic(|| __cw_native_{function.rust_symbol}({arguments}))?"),
            function.span,
            "abi_call",
        )
    else:
        native_call = f"__cw_native_{function.rust_symbol}({arguments})"
        if releases_gil:
            assert python_token is not None
            native_call = f"{python_token}.detach(move || {native_call})"
        writer.line(
            f"std::result::Result::Ok(__cw_catch_panic(|| {native_call})?)",
            function.span,
            "abi_call",
        )
    writer.leave()
    writer.line("}")


def _write_native_exceptions(writer: _Writer) -> None:
    """Declare private, identity-bearing failures for the generated ABI."""

    for _, rust_name in _NATIVE_EXCEPTION_TYPES:
        writer.line(
            f"{PYO3_CARGO_ALIAS}::create_exception!("
            f"__crabwalk_module, {rust_name}, "
            f"{PYO3_CARGO_ALIAS}::exceptions::PyRuntimeError);"
        )


def _write_buffer_support(writer: _Writer) -> None:
    """Emit a safe, call-scoped view over PyO3's alias-aware buffer cells."""

    writer.line("#[derive(Clone, Copy)]")
    writer.line(
        "struct __CwBuffer<'a, T: pyo3::buffer::Element> { "
        "values: &'a [pyo3::buffer::ReadOnlyCell<T>] }"
    )
    writer.line("impl<'a, T: pyo3::buffer::Element> __CwBuffer<'a, T> {")
    writer.enter()
    writer.line(
        "fn new(values: &'a [pyo3::buffer::ReadOnlyCell<T>]) -> Self { "
        "Self { values } }"
    )
    writer.line("fn len(&self) -> usize { self.values.len() }")
    writer.line("fn is_empty(&self) -> bool { self.values.is_empty() }")
    writer.line("fn get(&self, index: usize) -> T { self.values[index].get() }")
    writer.line(
        "fn iter(&self) -> impl Iterator<Item = T> + '_ { "
        "self.values.iter().map(pyo3::buffer::ReadOnlyCell::get) }"
    )
    writer.line("fn to_vec(&self) -> Vec<T> { self.iter().collect() }")
    writer.leave()
    writer.line("}")


def _write_text_column_support(writer: _Writer, type_ref: TypeRef) -> None:
    """Emit an immutable owned UTF-8 byte/offset column and its Python handle."""

    python_name, rust_name = owned_class_names(type_ref)
    writer.line("#[derive(Clone, Debug)]")
    writer.line("struct __CwTextColumn { data: Vec<u8>, offsets: Vec<usize> }")
    writer.line("impl __CwTextColumn {")
    writer.enter()
    writer.line("fn len(&self) -> usize { self.offsets.len() - 1 }")
    writer.line("fn is_empty(&self) -> bool { self.len() == 0 }")
    writer.line("fn total_bytes(&self) -> usize { self.data.len() }")
    writer.line("fn value_at(&self, index: usize) -> &str {")
    writer.enter()
    writer.line("let start = self.offsets[index];")
    writer.line("let end = self.offsets[index + 1];")
    writer.line(
        "std::str::from_utf8(&self.data[start..end])"
        '.expect("TextColumn UTF-8 invariant")'
    )
    writer.leave()
    writer.line("}")
    writer.line(
        "fn get(&self, index: usize) -> String { self.value_at(index).to_owned() }"
    )
    writer.line(
        "fn contains_at(&self, index: usize, marker: &str) -> bool { "
        "self.value_at(index).contains(marker) }"
    )
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{ value: Option<__CwTextColumn> }}")
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("#[new]")
    writer.line("fn new(data: Vec<u8>, offsets: Vec<usize>) -> PyResult<Self> {")
    writer.enter()
    writer.line("if offsets.is_empty() || offsets[0] != 0 {")
    writer.enter()
    writer.line(
        "return std::result::Result::Err(pyo3::exceptions::PyValueError::new_err("
        '"TextColumn offsets must start at zero"));'
    )
    writer.leave()
    writer.line("}")
    writer.line("if offsets[offsets.len() - 1] != data.len() {")
    writer.enter()
    writer.line(
        "return std::result::Result::Err(pyo3::exceptions::PyValueError::new_err("
        '"TextColumn final offset must equal the byte length"));'
    )
    writer.leave()
    writer.line("}")
    writer.line("for bounds in offsets.windows(2) {")
    writer.enter()
    writer.line("if bounds[0] > bounds[1] {")
    writer.enter()
    writer.line(
        "return std::result::Result::Err(pyo3::exceptions::PyValueError::new_err("
        '"TextColumn offsets must be monotonic"));'
    )
    writer.leave()
    writer.line("}")
    writer.line("if std::str::from_utf8(&data[bounds[0]..bounds[1]]).is_err() {")
    writer.enter()
    writer.line(
        "return std::result::Result::Err(pyo3::exceptions::PyUnicodeError::new_err("
        '"TextColumn segments must contain valid UTF-8"));'
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line(
        "std::result::Result::Ok(Self { value: std::option::Option::Some("
        "__CwTextColumn { data, offsets }) })"
    )
    writer.leave()
    writer.line("}")
    writer.line("fn __len__(&self) -> PyResult<usize> {")
    writer.enter()
    writer.line("self.value.as_ref().map(__CwTextColumn::len).ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line("fn to_python(&self) -> PyResult<(Vec<u8>, Vec<usize>)> {")
    writer.enter()
    writer.line("self.value.as_ref().map(|value| (")
    writer.enter()
    writer.line("value.data.clone(), value.offsets.clone()")
    writer.leave()
    writer.line(")).ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line("fn is_moved(&self) -> bool { self.value.is_none() }")
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{python_name}(rows={{}}, bytes={{}})", '
        "value.len(), value.total_bytes()),"
    )
    writer.line(f'std::option::Option::None => String::from("{python_name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _native_move_error(parameter: str, message: str = "value was moved") -> str:
    return (
        "__CwNativeMoveError::new_err(("
        f"{json.dumps(parameter)}, {json.dumps(message)}))"
    )


def _write_panic_boundary(writer: _Writer) -> None:
    writer.line(
        "fn __cw_panic_message(payload: Box<dyn std::any::Any + Send>) -> String {"
    )
    writer.enter()
    writer.line(
        "if let std::option::Option::Some(value) = payload.downcast_ref::<&str>() {"
    )
    writer.enter()
    writer.line("(*value).to_owned()")
    writer.leave()
    writer.line(
        "} else if let std::option::Option::Some(value) = "
        "payload.downcast_ref::<String>() {"
    )
    writer.enter()
    writer.line("value.clone()")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line('String::from("Rust panic without a string payload")')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "fn __cw_catch_panic<T, F: FnOnce() -> T>(operation: F) -> PyResult<T> {"
    )
    writer.enter()
    writer.line(
        "match std::panic::catch_unwind(std::panic::AssertUnwindSafe(operation)) {"
    )
    writer.enter()
    writer.line("std::result::Result::Ok(value) => std::result::Result::Ok(value),")
    writer.line("std::result::Result::Err(payload) => {")
    writer.enter()
    writer.line("let message = __cw_panic_message(payload);")
    writer.line("std::result::Result::Err(__CwNativePanicError::new_err(message))")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_thread_pool(writer: _Writer) -> None:
    writer.line("type __CwJob = Box<dyn FnOnce() + Send + 'static>;")
    writer.line(
        "type __CwWorkerFailure = std::sync::Arc<std::sync::Mutex<Option<String>>>;"
    )
    writer.line()
    writer.line(
        "fn __cw_record_worker_failure(failure: &__CwWorkerFailure, message: String) {"
    )
    writer.enter()
    writer.line(
        "let mut slot = failure.lock().unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("if slot.is_none() { *slot = std::option::Option::Some(message); }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwThreadPool {")
    writer.enter()
    writer.line("workers: Vec<__CwWorker>,")
    writer.line("sender: Option<std::sync::mpsc::Sender<__CwJob>>,")
    writer.line("failure: __CwWorkerFailure,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwThreadPool {")
    writer.enter()
    writer.line("fn new(size: usize) -> Self {")
    writer.enter()
    writer.line('assert!(size > 0, "thread pool size must be positive");')
    writer.line("let (sender, receiver) = std::sync::mpsc::channel();")
    writer.line("let receiver = std::sync::Arc::new(std::sync::Mutex::new(receiver));")
    writer.line("let failure = std::sync::Arc::new(std::sync::Mutex::new(None));")
    writer.line("let mut workers = Vec::with_capacity(size);")
    writer.line("for id in 0..size {")
    writer.enter()
    writer.line(
        "workers.push(__CwWorker::new(id, std::sync::Arc::clone(&receiver), "
        "std::sync::Arc::clone(&failure)));"
    )
    writer.leave()
    writer.line("}")
    writer.line("Self { workers, sender: std::option::Option::Some(sender), failure }")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn execute<F>(&self, operation: F)")
    writer.line("where")
    writer.enter()
    writer.line("F: FnOnce() + Send + 'static,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let job = Box::new(operation);")
    writer.line("self.sender.as_ref().unwrap().send(job).unwrap();")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn finish(mut self) -> Result<(), String> {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.line("let failure = {")
    writer.enter()
    writer.line(
        "let mut slot = self.failure.lock()"
        ".unwrap_or_else(|poisoned| poisoned.into_inner());"
    )
    writer.line("slot.take()")
    writer.leave()
    writer.line("};")
    writer.line(
        "match failure { "
        "std::option::Option::Some(message) => std::result::Result::Err(message), "
        "std::option::Option::None => std::result::Result::Ok(()) }"
    )
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn shutdown(&mut self) {")
    writer.enter()
    writer.line("drop(self.sender.take());")
    writer.line("for worker in self.workers.drain(..) {")
    writer.enter()
    writer.line("if let std::result::Result::Err(payload) = worker.thread.join() {")
    writer.enter()
    writer.line(
        "__cw_record_worker_failure(&self.failure, __cw_panic_message(payload));"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl Drop for __CwThreadPool {")
    writer.enter()
    writer.line("fn drop(&mut self) {")
    writer.enter()
    writer.line("self.shutdown();")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("struct __CwWorker {")
    writer.enter()
    writer.line("_id: usize,")
    writer.line("thread: std::thread::JoinHandle<()>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("impl __CwWorker {")
    writer.enter()
    writer.line(
        "fn new(id: usize, receiver: "
        "std::sync::Arc<std::sync::Mutex<std::sync::mpsc::Receiver<__CwJob>>>, "
        "failure: __CwWorkerFailure) "
        "-> Self {"
    )
    writer.enter()
    writer.line("let thread = std::thread::spawn(move || loop {")
    writer.enter()
    writer.line("let message = receiver.lock()")
    writer.enter()
    writer.line(".unwrap_or_else(|poisoned| poisoned.into_inner())")
    writer.line(".recv();")
    writer.leave()
    writer.line("match message {")
    writer.enter()
    writer.line("std::result::Result::Ok(job) => {")
    writer.enter()
    writer.line(
        "if let std::result::Result::Err(payload) = std::panic::catch_unwind("
        "std::panic::AssertUnwindSafe(job)) {"
    )
    writer.enter()
    writer.line("__cw_record_worker_failure(&failure, __cw_panic_message(payload));")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("std::result::Result::Err(_) => break,")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("});")
    writer.line("Self { _id: id, thread }")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _write_block_on_executor(writer: _Writer) -> None:
    """Emit the minimal std-only executor used by explicit rust.block_on calls.

    It is intentionally educational rather than a replacement for Tokio or async-std:
    a pending future yields the OS thread and is polled again. The implementation is
    safe Rust, deterministic, and sufficient for the self-contained Book examples.
    """

    writer.line("struct __CwNoopWake;")
    writer.line("impl std::task::Wake for __CwNoopWake {")
    writer.enter()
    writer.line("fn wake(self: std::sync::Arc<Self>) {}")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_yield_now() {")
    writer.enter()
    writer.line("let mut yielded = false;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if yielded {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("yielded = true;")
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_sleep_millis(milliseconds: u64) {")
    writer.enter()
    writer.line(
        "let deadline = std::time::Instant::now() "
        "+ std::time::Duration::from_millis(milliseconds);"
    )
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if std::time::Instant::now() >= deadline {")
    writer.enter()
    writer.line("std::task::Poll::Ready(())")
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_join2<A: std::future::Future, B: std::future::Future>(")
    writer.enter()
    writer.line("left: A,")
    writer.line("right: B,")
    writer.leave()
    writer.line(") -> (A::Output, B::Output) {")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("let mut left_output = None;")
    writer.line("let mut right_output = None;")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line("if left_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("left_output = std::option::Option::Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if right_output.is_none() {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("right_output = std::option::Option::Some(value);")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.line("if left_output.is_some() && right_output.is_some() {")
    writer.enter()
    writer.line(
        "std::task::Poll::Ready((left_output.take().unwrap(), "
        "right_output.take().unwrap()))"
    )
    writer.leave()
    writer.line("} else {")
    writer.enter()
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("async fn __cw_select2<A, B>(left: A, right: B) -> A::Output")
    writer.line("where")
    writer.enter()
    writer.line("A: std::future::Future,")
    writer.line("B: std::future::Future<Output = A::Output>,")
    writer.leave()
    writer.line("{")
    writer.enter()
    writer.line("let mut left = std::pin::pin!(left);")
    writer.line("let mut right = std::pin::pin!(right);")
    writer.line("std::future::poll_fn(move |context| {")
    writer.enter()
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(left.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line(
        "if let std::task::Poll::Ready(value) = "
        "std::future::Future::poll(right.as_mut(), context) {"
    )
    writer.enter()
    writer.line("return std::task::Poll::Ready(value);")
    writer.leave()
    writer.line("}")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line(
        "async fn __cw_recv_async<T>(receiver: &std::sync::mpsc::Receiver<T>) -> T {"
    )
    writer.enter()
    writer.line("std::future::poll_fn(|context| match receiver.try_recv() {")
    writer.enter()
    writer.line("std::result::Result::Ok(value) => std::task::Poll::Ready(value),")
    writer.line("std::result::Result::Err(std::sync::mpsc::TryRecvError::Empty) => {")
    writer.enter()
    writer.line("context.waker().wake_by_ref();")
    writer.line("std::task::Poll::Pending")
    writer.leave()
    writer.line("}")
    writer.line(
        "std::result::Result::Err("
        "std::sync::mpsc::TryRecvError::Disconnected) => "
        'panic!("async channel disconnected"),'
    )
    writer.leave()
    writer.line("}).await")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __cw_block_on<F: std::future::Future>(future: F) -> F::Output {")
    writer.enter()
    writer.line(
        "let waker = std::task::Waker::from(std::sync::Arc::new(__CwNoopWake));"
    )
    writer.line("let mut context = std::task::Context::from_waker(&waker);")
    writer.line("let mut future = std::pin::pin!(future);")
    writer.line("loop {")
    writer.enter()
    writer.line("match std::future::Future::poll(future.as_mut(), &mut context) {")
    writer.enter()
    writer.line("std::task::Poll::Ready(value) => return value,")
    writer.line("std::task::Poll::Pending => std::thread::yield_now(),")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def function_releases_gil(function: FunctionIR) -> bool:
    """Whether an exported wrapper can detach from Python for the native call."""

    effects = set(function.effects)
    if function.release_gil:
        return (
            function.exported
            and Effect.PYTHON_RUNTIME not in effects
            and all(
                not _type_retains_python_borrow_for_detach(parameter.type_ref)
                for parameter in function.parameters
            )
        )
    if effects & {
        Effect.BORROWED_BUFFER,
        Effect.OPAQUE_CRATE_CALL,
        Effect.PYTHON_RUNTIME,
        Effect.GLOBAL_MUTATION,
        Effect.UNSAFE_MEMORY,
        Effect.UNSAFE_FFI,
    }:
        return False
    if any(
        parameter.type_ref.ownership not in {None, "Shared"}
        for parameter in function.parameters
    ):
        return False
    safe_names = {
        "i8",
        "i16",
        "i32",
        "i64",
        "i128",
        "isize",
        "u8",
        "u16",
        "u32",
        "u64",
        "u128",
        "usize",
        "f32",
        "f64",
        "bool",
        "char",
        "Unit",
    }
    return (
        all(
            parameter.type_ref.rust_name in safe_names
            or parameter.type_ref.ownership == "Shared"
            for parameter in function.parameters
        )
        and function.return_type.rust_name in safe_names
    )


def _type_retains_python_borrow_for_detach(type_ref: TypeRef) -> bool:
    if type_ref.ownership in {"Owned", "Shared"}:
        return False
    if type_ref.ownership in {"Ref", "Mut"}:
        return True
    if type_ref.rust_name in {"Buffer", "Str", "LifetimeRef"}:
        return True
    return any(
        _type_retains_python_borrow_for_detach(value) for value in type_ref.arguments
    )


def _owned_vector_types(ir: PackageIR) -> tuple[TypeRef, ...]:
    values: dict[str, TypeRef] = {}
    for function in ir.functions:
        if not function.exported:
            continue
        for parameter in function.parameters:
            if (
                parameter.type_ref.ownership is not None
                and parameter.type_ref.underlying.rust_name == "Vec"
            ):
                vector = parameter.type_ref.underlying
                values[vector.render()] = vector
        if (
            function.return_type.ownership == "Owned"
            and function.return_type.underlying.rust_name == "Vec"
        ):
            vector = function.return_type.underlying
            values[vector.render()] = vector
    return tuple(values[key] for key in sorted(values))


def _owned_text_column_type(ir: PackageIR) -> TypeRef | None:
    for function in ir.functions:
        if not function.exported:
            continue
        if any(
            parameter.type_ref.ownership is not None
            and parameter.type_ref.underlying.rust_name == "TextColumn"
            for parameter in function.parameters
        ):
            return TypeRef("TextColumn")
        if (
            function.return_type.ownership == "Owned"
            and function.return_type.underlying.rust_name == "TextColumn"
        ):
            return TypeRef("TextColumn")
    return None


def _owned_external_types(ir: PackageIR) -> tuple[ExternalType, ...]:
    values: dict[str, ExternalType] = {}
    for function in ir.functions:
        if not function.exported:
            continue
        for parameter in function.parameters:
            underlying = parameter.type_ref.underlying
            if parameter.type_ref.ownership is not None and isinstance(
                underlying, ExternalType
            ):
                values[underlying.render()] = underlying
        return_type = function.return_type.underlying
        if function.return_type.ownership == "Owned" and isinstance(
            return_type, ExternalType
        ):
            values[return_type.render()] = return_type
    return tuple(values[key] for key in sorted(values))


def _write_owned_external_class(writer: _Writer, type_ref: ExternalType) -> None:
    """Emit one opaque, move-aware Python holder without crate trait assumptions."""

    python_name, rust_name = owned_class_names(type_ref)
    rendered = type_ref.render()
    display = type_ref.display()
    writer.line(f'#[pyclass(unsendable, name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{rendered}>,")
    writer.leave()
    writer.line("}")
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line(
        f'if self.value.is_some() {{ String::from("{display}(<opaque>)") }} '
        f'else {{ String::from("{display}(<moved>)") }}'
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _shared_types(ir: PackageIR) -> tuple[TypeRef, ...]:
    values = {
        parameter.type_ref.underlying.render(): parameter.type_ref.underlying
        for function in ir.functions
        if function.exported
        for parameter in function.parameters
        if parameter.type_ref.ownership == "Shared"
    }
    return tuple(values[key] for key in sorted(values))


def _write_shared_class(writer: _Writer, type_ref: TypeRef) -> None:
    """Emit a frozen Python wrapper around ``Arc<T>`` for proven-safe payloads."""

    python_name, rust_name = shared_class_names(type_ref)
    _, owned_rust_name = owned_class_names(type_ref)
    rendered = type_ref.render()
    writer.line(f'#[pyclass(frozen, name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{ value: std::sync::Arc<{rendered}> }}")
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("#[new]")
    writer.line(
        f"fn new(mut source: PyRefMut<'_, {owned_rust_name}>) -> PyResult<Self> {{"
    )
    writer.enter()
    writer.line("let value = source.value.take().ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error("", "cannot freeze a moved value"))
    writer.leave()
    writer.line("})?;")
    writer.line("std::result::Result::Ok(Self { value: std::sync::Arc::new(value) })")
    writer.leave()
    writer.line("}")
    writer.line(
        f"fn snapshot(&self) -> {owned_rust_name} {{ {owned_rust_name} {{ "
        "value: std::option::Option::Some((*self.value).clone()) } }"
    )
    if type_ref.rust_name in {"Vec", "TextColumn"}:
        writer.line("fn __len__(&self) -> usize { self.value.len() }")
    writer.line("fn is_moved(&self) -> bool { false }")
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line(
        f'format!("{python_name}(shared, strong_count={{}})", '
        "std::sync::Arc::strong_count(&self.value))"
    )
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _bulk_extractor_name(type_ref: TypeRef) -> str:
    identity = f"{type_ref.display()}|{type_ref.render()}".encode()
    return f"__cw_extract_{hashlib.sha256(identity).hexdigest()[:20]}"


def _write_bulk_input_extractors(
    writer: _Writer,
    roots: tuple[TypeRef, ...],
    structs_by_symbol: dict[str, StructIR],
    enums_by_symbol: dict[str, EnumIR],
) -> None:
    """Emit one-call Python mapping -> native domain construction helpers."""

    discovered: dict[str, TypeRef] = {}
    pending = list(roots)
    while pending:
        type_ref = pending.pop()
        name = _bulk_extractor_name(type_ref)
        if name in discovered:
            continue
        discovered[name] = type_ref
        pending.extend(type_ref.arguments)
        struct = structs_by_symbol.get(type_ref.rust_name)
        if struct is not None:
            pending.extend(field.type_ref for field in struct.fields)
        enum = enums_by_symbol.get(type_ref.rust_name)
        if enum is not None:
            pending.extend(
                field.type_ref for variant in enum.variants for field in variant.fields
            )

    for name in sorted(discovered):
        _write_bulk_input_extractor(
            writer,
            name,
            discovered[name],
            structs_by_symbol,
            enums_by_symbol,
        )
        writer.line()


def _write_bulk_input_extractor(
    writer: _Writer,
    name: str,
    type_ref: TypeRef,
    structs_by_symbol: dict[str, StructIR],
    enums_by_symbol: dict[str, EnumIR],
) -> None:
    writer.line(
        f"fn {name}(value: &Bound<'_, PyAny>, path: &str) "
        f"-> PyResult<{type_ref.render()}> {{"
    )
    writer.enter()
    struct = structs_by_symbol.get(type_ref.rust_name)
    enum = enums_by_symbol.get(type_ref.rust_name)
    if struct is not None:
        _write_bulk_struct_extractor(writer, struct)
    elif enum is not None:
        _write_bulk_handle_extractor(writer, enum.type_ref)
    elif type_ref.rust_name == "Option" and len(type_ref.arguments) == 1:
        child = type_ref.arguments[0]
        writer.line("if value.is_none() {")
        writer.enter()
        writer.line("std::result::Result::Ok(std::option::Option::None)")
        writer.leave()
        writer.line("} else {")
        writer.enter()
        writer.line(
            "std::result::Result::Ok(std::option::Option::Some("
            f"{_bulk_extractor_name(child)}(value, path)?))"
        )
        writer.leave()
        writer.line("}")
    elif type_ref.rust_name == "Vec" and len(type_ref.arguments) == 1:
        _write_bulk_sequence_extractor(writer, type_ref.arguments[0], array_length=None)
    elif type_ref.rust_name == "Array" and len(type_ref.arguments) == 1:
        _write_bulk_sequence_extractor(
            writer,
            type_ref.arguments[0],
            array_length=type_ref.const_value,
        )
    elif type_ref.rust_name == "Tuple" and type_ref.arguments:
        writer.line(
            "let tuple = value.cast::<pyo3::types::PyTuple>().map_err(|_| "
            "pyo3::exceptions::PyTypeError::new_err(format!("
            '"{}: expected tuple", path)))?;'
        )
        writer.line(f"if tuple.len() != {len(type_ref.arguments)} {{")
        writer.enter()
        writer.line(
            "return std::result::Result::Err("
            "pyo3::exceptions::PyValueError::new_err(format!("
            f'"{{}}: expected {len(type_ref.arguments)} tuple items", path)));'
        )
        writer.leave()
        writer.line("}")
        tuple_values: list[str] = []
        for index, child in enumerate(type_ref.arguments):
            local = f"__cw_tuple_{index}"
            writer.line(f"let {local} = tuple.get_item({index})?;")
            tuple_values.append(
                f"{_bulk_extractor_name(child)}(&{local}, "
                f'&format!("{{}}[{index}]", path))?'
            )
        suffix = "," if len(tuple_values) == 1 else ""
        writer.line(
            "std::result::Result::Ok((" + ", ".join(tuple_values) + suffix + "))"
        )
    elif type_ref.rust_name == "HashMap" and len(type_ref.arguments) == 2:
        key, item = type_ref.arguments
        writer.line(
            "let mapping = value.cast::<pyo3::types::PyDict>().map_err(|_| "
            "pyo3::exceptions::PyTypeError::new_err(format!("
            '"{}: expected mapping", path)))?;'
        )
        writer.line(
            "let mut output = std::collections::HashMap::with_capacity(mapping.len());"
        )
        writer.line("for (__cw_key, __cw_value) in mapping.iter() {")
        writer.enter()
        writer.line(
            f"let __cw_native_key = {_bulk_extractor_name(key)}("
            '&__cw_key, &format!("{} mapping key", path))?;'
        )
        writer.line(
            f"let __cw_native_value = {_bulk_extractor_name(item)}("
            '&__cw_value, &format!("{} mapping value", path))?;'
        )
        writer.line("output.insert(__cw_native_key, __cw_native_value);")
        writer.leave()
        writer.line("}")
        writer.line("std::result::Result::Ok(output)")
    else:
        writer.line(
            f"value.extract::<{type_ref.render()}>().map_err(|error| "
            "pyo3::exceptions::PyTypeError::new_err(format!("
            '"{}: {}", path, error)))'
        )
    writer.leave()
    writer.line("}")


def _write_bulk_handle_extractor(writer: _Writer, type_ref: TypeRef) -> None:
    _, domain_class = owned_class_names(type_ref)
    writer.line(
        f"if let std::result::Result::Ok(handle) = value.extract::<PyRef<'_, {domain_class}>>() {{"
    )
    writer.enter()
    writer.line("let stored = handle.value.as_ref().ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})?;")
    writer.line("return std::result::Result::Ok(stored.clone());")
    writer.leave()
    writer.line("}")
    writer.line(
        "std::result::Result::Err(pyo3::exceptions::PyTypeError::new_err("
        f'format!("{{}}: expected {type_ref.display()} handle", path)))'
    )


def _write_bulk_struct_extractor(writer: _Writer, struct: StructIR) -> None:
    _, domain_class = owned_class_names(struct.type_ref)
    writer.line(
        f"if let std::result::Result::Ok(handle) = value.extract::<PyRef<'_, {domain_class}>>() {{"
    )
    writer.enter()
    writer.line("let stored = handle.value.as_ref().ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})?;")
    writer.line("return std::result::Result::Ok(stored.clone());")
    writer.leave()
    writer.line("}")
    writer.line(
        "let mapping = value.cast::<pyo3::types::PyDict>().map_err(|_| "
        "pyo3::exceptions::PyTypeError::new_err(format!("
        f'"{{}}: expected {struct.qualified_name} handle or mapping", path)))?;'
    )
    field_values: list[str] = []
    for index, field in enumerate(struct.fields):
        raw = f"__cw_raw_field_{index}"
        native = f"__cw_native_field_{index}"
        writer.line(
            f"let {raw} = mapping.get_item({json.dumps(field.name)})?.ok_or_else(|| "
            "pyo3::exceptions::PyTypeError::new_err(format!("
            f'"{{}}: missing field {field.name}", path)))?;'
        )
        writer.line(
            f"let {native} = {_bulk_extractor_name(field.type_ref)}("
            f'&{raw}, &format!("{{}}.{field.name}", path))?;'
        )
        field_values.append(f"{field.rust_name}: {native}")
    writer.line(
        f"std::result::Result::Ok({struct.symbol} {{ " + ", ".join(field_values) + " })"
    )


def _write_bulk_sequence_extractor(
    writer: _Writer,
    child: TypeRef,
    *,
    array_length: int | None,
) -> None:
    writer.line("let mut output = Vec::with_capacity(value.len()?);")
    writer.line("for (index, item) in value.try_iter()?.enumerate() {")
    writer.enter()
    writer.line("let item = item?;")
    writer.line(
        f"output.push({_bulk_extractor_name(child)}("
        '&item, &format!("{}[{}]", path, index))?);'
    )
    writer.leave()
    writer.line("}")
    if array_length is None:
        writer.line("std::result::Result::Ok(output)")
        return
    writer.line(f"if output.len() != {array_length} {{")
    writer.enter()
    writer.line(
        "return std::result::Result::Err("
        "pyo3::exceptions::PyValueError::new_err(format!("
        f'"{{}}: expected {array_length} items", path)));'
    )
    writer.leave()
    writer.line("}")
    writer.line(
        "output.try_into().map_err(|_| "
        "pyo3::exceptions::PyValueError::new_err(format!("
        f'"{{}}: expected {array_length} items", path)))'
    )


def _write_owned_vector_class(
    writer: _Writer,
    vector_type: TypeRef,
    domains_by_symbol: dict[str, TypeRef],
) -> None:
    python_name, rust_name = owned_class_names(vector_type)
    rendered = vector_type.render()
    element_type = vector_type.arguments[0]
    contains_domain = _contains_domain(element_type, domains_by_symbol)
    writer.line(f'#[pyclass(name = "{python_name}")]')
    writer.line(f"struct {rust_name} {{")
    writer.enter()
    writer.line(f"value: Option<{rendered}>,")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("#[pymethods]")
    writer.line(f"impl {rust_name} {{")
    writer.enter()
    writer.line("#[new]")
    if not contains_domain:
        writer.line(f"fn new(value: {rendered}) -> Self {{")
        writer.enter()
        writer.line("Self { value: std::option::Option::Some(value) }")
        writer.leave()
        writer.line("}")
    else:
        writer.line("fn new(value: &Bound<'_, PyAny>) -> PyResult<Self> {")
        writer.enter()
        constructor_names = EmissionNames.reserving("value")
        values = constructor_names.temporary("owned_values")
        item = constructor_names.temporary("owned_item")
        index = constructor_names.temporary("owned_index")
        writer.line(f"let mut {values} = Vec::with_capacity(value.len()?);")
        writer.line(f"for ({index}, {item}) in value.try_iter()?.enumerate() {{")
        writer.enter()
        writer.line(f"let {item} = {item}?;")
        writer.line(
            f"{values}.push({_bulk_extractor_name(element_type)}("
            f'&{item}, &format!("vector element {{}}", {index}))?);'
        )
        writer.leave()
        writer.line("}")
        writer.line(
            "std::result::Result::Ok(Self { "
            f"value: std::option::Option::Some({values}) }})"
        )
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn __len__(&self) -> PyResult<usize> {")
    writer.enter()
    writer.line("self.value.as_ref().map(|value| value.len()).ok_or_else(|| {")
    writer.enter()
    writer.line(_native_move_error(""))
    writer.leave()
    writer.line("})")
    writer.leave()
    writer.line("}")
    writer.line()
    if not contains_domain:
        writer.line(f"fn to_python(&self) -> PyResult<{rendered}> {{")
        writer.enter()
        writer.line("self.value.as_ref().cloned().ok_or_else(|| {")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})")
        writer.leave()
        writer.line("}")
    else:
        to_python_names = EmissionNames.reserving("self", "py")
        values = to_python_names.temporary("stored_values")
        writer.line(
            "fn to_python(&self, py: Python<'_>) -> "
            f"PyResult<{_domain_output_type(vector_type, domains_by_symbol)}> {{"
        )
        writer.enter()
        writer.line(f"let {values} = self.value.as_ref().ok_or_else(|| {{")
        writer.enter()
        writer.line(_native_move_error(""))
        writer.leave()
        writer.line("})?;")
        writer.line(
            _domain_output_conversion(
                values,
                vector_type,
                domains_by_symbol,
                to_python_names,
            )
        )
        writer.leave()
        writer.line("}")
    writer.line()
    writer.line("fn is_moved(&self) -> bool {")
    writer.enter()
    writer.line("self.value.is_none()")
    writer.leave()
    writer.line("}")
    writer.line()
    writer.line("fn __repr__(&self) -> String {")
    writer.enter()
    writer.line("match &self.value {")
    writer.enter()
    writer.line(
        f'std::option::Option::Some(value) => format!("{python_name}({{:?}})", value),'
    )
    writer.line(f'std::option::Option::None => String::from("{python_name}(<moved>)"),')
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")
    writer.leave()
    writer.line("}")


def _wrapper_parameter(parameter: ParameterIR) -> str:
    ownership = parameter.type_ref.ownership
    if ownership is None and parameter.type_ref.rust_name == "Buffer":
        return f"{parameter.rust_name}: &Bound<'_, PyAny>"
    if ownership is None:
        return f"{parameter.rust_name}: {parameter.type_ref.render()}"
    vector = parameter.type_ref.underlying
    if ownership == "Shared":
        _, rust_class = shared_class_names(vector)
        return f"{parameter.rust_name}: PyRef<'_, {rust_class}>"
    _, rust_class = owned_class_names(vector)
    if ownership == "Ref":
        return f"{parameter.rust_name}: PyRef<'_, {rust_class}>"
    return f"mut {parameter.rust_name}: PyRefMut<'_, {rust_class}>"


def _write_wrapper_extraction(
    writer: _Writer,
    parameter: ParameterIR,
    extracted_name: str | None,
    python_token: str | None,
    untyped_buffer_name: str | None,
) -> None:
    ownership = parameter.type_ref.ownership
    if ownership is None and parameter.type_ref.rust_name == "Buffer":
        assert extracted_name is not None
        assert python_token is not None
        assert untyped_buffer_name is not None
        cells_name = f"{extracted_name}_cells"
        message_prefix = f"argument '{parameter.name}'"
        element = parameter.type_ref.arguments[0].render()
        writer.line(
            (
                "// A valid zero-length Python buffer may expose a null or "
                "unaligned data pointer."
            ),
            parameter.span,
            "buffer_boundary",
        )
        writer.line(
            "// Use Rust's canonical aligned empty slice; non-empty buffers remain alignment-checked.",
            parameter.span,
            "buffer_boundary",
        )
        writer.line(
            (
                f"let {cells_name}: &[pyo3::buffer::ReadOnlyCell<{element}>] = "
                f"if {untyped_buffer_name}.item_count() == 0 {{ &[] }} else {{ "
                f"{untyped_buffer_name}.as_typed::<{element}>()?.as_slice({python_token})"
                ".ok_or_else(|| pyo3::exceptions::PyBufferError::new_err("
                f"{json.dumps(message_prefix + ' must be C-contiguous')}))? }};"
            ),
            parameter.span,
            "buffer_boundary",
        )
        writer.line(
            f"let {extracted_name} = __CwBuffer::new({cells_name});",
            parameter.span,
            "buffer_boundary",
        )
        return
    if ownership is None:
        assert extracted_name is None
        return
    assert extracted_name is not None
    if ownership == "Shared":
        writer.line(
            f"let {extracted_name} = {parameter.rust_name}.value.clone();",
            parameter.span,
            "shared_ownership_boundary",
        )
        return
    access = {
        "Owned": "take()",
        "Ref": "as_ref()",
        "Mut": "as_mut()",
    }[ownership]
    writer.line(
        (
            f"let {extracted_name} = "
            f"{parameter.rust_name}.value.{access}.ok_or_else(|| "
            f"{_native_move_error(parameter.name)})?;"
        ),
        parameter.span,
        "ownership_boundary",
    )


def _write_wrapper_ownership_preflight(
    writer: _Writer,
    parameter: ParameterIR,
) -> None:
    if parameter.type_ref.ownership in {None, "Shared"}:
        return
    writer.line(
        (
            f"if {parameter.rust_name}.value.is_none() {{ "
            f"return std::result::Result::Err("
            f"{_native_move_error(parameter.name)}); }}"
        ),
        parameter.span,
        "ownership_preflight",
    )


def _write_wrapper_buffer_preflight(
    writer: _Writer,
    parameter: ParameterIR,
    untyped_buffer_name: str | None,
) -> None:
    if (
        parameter.type_ref.ownership is not None
        or parameter.type_ref.rust_name != "Buffer"
    ):
        return
    assert untyped_buffer_name is not None
    message_prefix = f"argument '{parameter.name}'"
    element = parameter.type_ref.arguments[0].render()
    writer.line(
        (
            f"let {untyped_buffer_name} = "
            f"pyo3::buffer::PyUntypedBuffer::get({parameter.rust_name})?;"
        ),
        parameter.span,
        "buffer_preflight",
    )
    writer.line(
        (
            f"if {untyped_buffer_name}.dimensions() != 1 {{ "
            "return std::result::Result::Err("
            "pyo3::exceptions::PyBufferError::new_err("
            f"{json.dumps(message_prefix + ' must be one-dimensional')})); }}"
        ),
        parameter.span,
        "buffer_preflight",
    )
    writer.line(
        (
            f"if !{untyped_buffer_name}.readonly() {{ "
            "return std::result::Result::Err("
            "pyo3::exceptions::PyBufferError::new_err("
            f"{json.dumps(message_prefix + ' must be read-only')})); }}"
        ),
        parameter.span,
        "buffer_preflight",
    )
    writer.line(
        (
            f"if !{untyped_buffer_name}.is_c_contiguous() {{ "
            "return std::result::Result::Err("
            "pyo3::exceptions::PyBufferError::new_err("
            f"{json.dumps(message_prefix + ' must be C-contiguous')})); }}"
        ),
        parameter.span,
        "buffer_preflight",
    )
    writer.line(
        (
            f"if {untyped_buffer_name}.item_size() != std::mem::size_of::<{element}>() "
            f"|| !<{element} as pyo3::buffer::Element>::is_compatible_format("
            f"{untyped_buffer_name}.format()) {{ "
            "return std::result::Result::Err("
            "pyo3::exceptions::PyBufferError::new_err("
            f"{json.dumps(message_prefix + ' has an incompatible element format')})); }}"
        ),
        parameter.span,
        "buffer_preflight",
    )
